### PR TITLE
Docs: add logo to siderbar

### PR DESCRIPTION
**Pull request by njzjz**

### CODE REVIEW

**Comment by njzjz** [comment]
Screenshot from 2022-12-25 15-57-09

The logo is not transparent - is there a logo in SVG format?

**Comment by caic99** [comment]
> The logo is not transparent - is there a logo in SVG format?

Not yet. I'll ask if there is an SVG logo for this PR.

**Review by dyzheng — APPROVED** [review]

**Comment by caic99** [comment]
@dyzheng Would you provide me the latest logo design?

**Comment by caic99** [comment]
Completed in #1839. @njzjz Thanks!

**Pull request closed without merging**
