### PR TITLE
Fix: matrix bug in uspp

### LINKED ISSUE #4370: STDERR: abacus: /abacus-develop/source/module_base/matrix.h:46: const double &ModuleBase::matrix::operator()(const int, const int) const: Assertion `ir<nr' failed.
### Describe the bug

in stdout:
```
                                                                                     
                              ABACUS v3.6.5
               Atomic-orbital Based Ab-initio Computation at UStc                    
                     Website: http://abacus.ustc.edu.cn/                             
               Documentation: https://abacus.deepmodeling.com/                       
                  Repository: https://github.com/abacusmodeling/abacus-develop       
                              https://github.com/deepmodeling/abacus-develop         
                      Commit: 10c5281 (Thu Jun 13 09:35:14 2024 +0800)
 Thu Jun 13 15:01:30 2024
 MAKE THE DIR         : OUT.ABACUS/
 RUNNING WITH DEVICE  : CPU / Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz
 UNIFORM GRID DIM        : 15 * 15 * 15
 UNIFORM GRID DIM(BIG)   : 15 * 15 * 15
 DONE(0.0412196  SEC) : SETUP UNITCELL
 DONE(0.120171   SEC) : SYMMETRY
 DONE(53.1812    SEC) : INIT K-POINTS
 ---------------------------------------------------------
 Ion relaxation calculations
 ---------------------------------------------------------
 SPIN    KPOINTS         PROCESSORS  
 1       5728            16          
 ---------------------------------------------------------
 Use plane wave basis
 ---------------------------------------------------------
 ELEMENT NATOM       XC          
 H       1           
 ---------------------------------------------------------
 Initial plane wave basis and FFT box
 ---------------------------------------------------------
 DONE(53.1885    SEC) : INIT PLANEWAVE
 MEMORY FOR PSI (MB)  : 10.5757
 DONE(53.1892    SEC) : LOCAL POTENTIAL
 DONE(53.2252    SEC) : NON-LOCAL POTENTIAL
 DONE(53.2339    SEC) : INIT BASIS
 -------------------------------------------
 STEP OF RELAXATION : 1
 -------------------------------------------
 START CHARGE      : atomic
STDERR: abacus: /abacus-develop/source/module_base/matrix.h:46: const double &ModuleBase::matrix::operator()(const int, const int) const: Assertion `ir<nr' failed.
===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 38 RUNNING AT dp-lbg-471-13210984
=   KILLED BY SIGNAL: 9 (Killed)
===================================================================================
```
Please try with:
[58381245-23fa-459d-9396-336e4a14978e.zip](https://github.com/user-attachments/files/15815428/58381245-23fa-459d-9396-336e4a14978e.zip)

### Expected behavior

_No response_

### To Reproduce

_No response_

### Environment

_No response_

### Additional Context

_No response_

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

### LINKED ISSUE #4371: USPP PW calculation aborts with no information
### Describe the bug

see the following:
```
                                                                                     
                              ABACUS v3.6.5

               Atomic-orbital Based Ab-initio Computation at UStc                    

                     Website: http://abacus.ustc.edu.cn/                             
               Documentation: https://abacus.deepmodeling.com/                       
                  Repository: https://github.com/abacusmodeling/abacus-develop       
                              https://github.com/deepmodeling/abacus-develop         
                      Commit: 10c5281 (Thu Jun 13 09:35:14 2024 +0800)

 Thu Jun 13 15:01:35 2024
 MAKE THE DIR         : OUT.ABACUS/
 RUNNING WITH DEVICE  : CPU / Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz
 UNIFORM GRID DIM        : 15 * 15 * 15
 UNIFORM GRID DIM(BIG)   : 15 * 15 * 15
 DONE(0.0462065  SEC) : SETUP UNITCELL
 DONE(0.138757   SEC) : SYMMETRY
 DONE(48.0371    SEC) : INIT K-POINTS
 ---------------------------------------------------------
 Ion relaxation calculations
 ---------------------------------------------------------
 SPIN    KPOINTS         PROCESSORS  
 1       5216            16          
 ---------------------------------------------------------
 Use plane wave basis
 ---------------------------------------------------------
 ELEMENT NATOM       XC          
 H       1           
 ---------------------------------------------------------
 Initial plane wave basis and FFT box
 ---------------------------------------------------------
 DONE(48.0426    SEC) : INIT PLANEWAVE
 MEMORY FOR PSI (MB)  : 9.63037
 DONE(48.0432    SEC) : LOCAL POTENTIAL
 DONE(48.0797    SEC) : NON-LOCAL POTENTIAL
 DONE(48.0885    SEC) : INIT BASIS
 -------------------------------------------
 STEP OF RELAXATION : 1
 -------------------------------------------
 START CHARGE      : atomic

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 40 RUNNING AT dp-lbg-471-13210994
=   KILLED BY SIGNAL: 9 (Killed)
===================================================================================

```
please try with:
[3672fc4d-a8db-4875-b235-70a667cb85dc.zip](https://github.com/user-attachments/files/15815484/3672fc4d-a8db-4875-b235-70a667cb85dc.zip)

### Expected behavior

_No response_

### To Reproduce

_No response_

### Environment

_No response_

### Additional Context

_No response_

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

### PR DESCRIPTION
**Pull request by YuLiu98**
### Linked Issue
Fix #4370 
Fix #4371

### CODE REVIEW

**Comment by kirk0830** [comment]
Thanks for your contribution, so seems there is something wrong with the overloaded operator() or wrong memory address was provided?
So if possible, you can post the test case that can be run smoothly now, then other code reviewers can also quickly evaluate this PR.
Best.

**Comment by YuLiu98** [comment]
> Thanks for your contribution, so seems there is something wrong with the overloaded operator() or wrong memory address was provided? So if possible, you can post the test case that can be run smoothly now, then other code reviewers can also quickly evaluate this PR. Best.

Do you mean a CI test should be added? 

This is the example of issue #4370 :
[issue4370.tar.gz](https://github.com/user-attachments/files/15841915/issue4370.tar.gz)

**Comment by mohanchen** [comment]
We will accept this PR now, more discussions are welcome.

**Review by mohanchen — APPROVED** [review]
LGTM

**Pull request merged**
