### PR TITLE
Refactor: modify EXX realx/md calculation framework

### PR DESCRIPTION
**Pull request by 1041176461**
The new EXX relax/md framework does not need to repeat the PBE calculation to build the density matrix for subsequent ion steps except step 0. Instead, it directly reads the density matrix of the previous step to perform EXX self-consistent calculation, reducing unnecessary self-consistent calculations.

 Here are some comparsion
1. For relax, `exx_separate_loop 1`, left -> new, right -> old
image

2. For relax, `exx_separate_loop 0`, left -> new, right -> old
image

3. For md, `exx_separate_loop 1`, left -> new, right -> old
image

4. For md, `exx_separate_loop 0`, left -> new, right -> old
image

### CODE REVIEW

**Comment by 1041176461** [comment]
For EXX relax/md Integration Test, `exx_separate_loop       1` and `exx_hybrid_step         2` settings are used. However, the first two EXX outer steps do not fully converge, and the results of the new and old frameworks are different. According to my test above, although the first few outer steps are different, they finally converged to consistent results. Do you have any suggestions on integration testing? @maki49

**Comment by maki49** [comment]
@1041176461 You can change the reference results of the related cases.
I find nothing wrong with your code, so I'm confused about why the energy difference is larger than before in first exx-loop (compared to the following exx-loop) in the separate-loop case ( as figure 1 and 3)...
"The density matrix difference resulting from the structure difference contributes more than the difference between pbe and hybrid functional"? hmm... seems make sense

**Comment by 1041176461** [comment]
@maki49 Thanks! I changed "result.ref" of tests "285_NO_KP_RE_HSE", "286_NO_KP_CR_HSE", "385_NO_GO_RE_S1_HSE" and "386_NO_GO_MD_S1_HSE". I guess density matrix extrapolation may be a good way to reduce the difference, and corresponding implementations are planned.

**Review by YuLiu98 — APPROVED** [review]

**Review by maki49 — APPROVED** [review]

**Review by maki49 — APPROVED** [review]

**Review by WHUweiqingzhou — CHANGES_REQUESTED** [review]
I notice you change the ref. I think these changes should be reviewed by more relevant developers. Could you make a review @PeizeLin ?

**Review by WHUweiqingzhou — APPROVED** [review]

**Comment by PeizeLin** [comment]
> I notice you change the ref. I think these changes should be reviewed by more relevant developers. Could you make a review @PeizeLin ?

Since all the Integration Tests are unconverged, the older refs are meaningless when the loop is changed.

**Review by mohanchen — APPROVED** [review]

**Pull request merged**
