### PR TITLE
INPUT parameters refactor

### LINKED ISSUE #809: INPUT parameters refactor
Some INPUT parameters are needed to be refactored, details are listed as follows:

1) `seed` -> `pw_seed`
2) `npool` -> `pw_kpar`
3) `renormwithmesh` -> `pseudo_rmesh`
4) `niter` -> `scf_nmax`
5) `ethr` -> `diag_thr_e`
6) `dr2` -> `scf_thr`
7) `diago_cg_maxiter` -> `diag_cg_nmax`
8) `smearing` -> `smearing_method`
9) `sigma` -> `smearing_sigma`
10) `atom_file` -> `stru_file`
11) `start_wfc` -> `init_wfc`
12) `start_charge` -> `init_chg`
13) `set_vel` -> `init_vel`
14) `out_wf` -> `out_wfc_pw`
15) `out_lowf` -> `out_wfc_lcao`
16) `out_wf_r` -> `out_wfc_r`
17) `out_charge` -> `out_chg`
18) `out_potential` -> `out_pot`
19) `mulliken` -> `out_mul`
20) `out_hs` -> `out_mat_hs`
21) `out_hs2` -> `out_mat_hs2`
22) `out_r_matrix` -> `out_mat_r`
23) `charge_extrap` -> `chg_extrap`
24) `move_method` -> `relax_method`
25) `cg_threshold` -> `relax_cg_thr`
26) `force` -> `cal_force`
27) `nstep` -> `relax_nstep`
28) `force_set` -> `out_force`
29) `stress` -> `cal_stress`
30) `trust_radius_max` -> `bfgs_rmax`
31) `trust_radius_min` -> `bfgs_rmin`
32) `trust_radius_ini` -> `bfgs_init`

### PR DESCRIPTION
**Pull request by YuLiu98**
Some INPUT parameters are needed to be refactored, details are listed as follows:

1) `seed` -> `pw_seed`
2) `npool` -> `pw_kpar`
3) `renormwithmesh` -> `pseudo_rmesh`
4) `niter` -> `scf_nmax`
5) `ethr` -> `diag_thr_e`
6) `dr2` -> `scf_thr`
7) `diago_cg_maxiter` -> `diag_cg_nmax`
8) `smearing` -> `smearing_method`
9) `sigma` -> `smearing_sigma`
10) `atom_file` -> `stru_file`
11) `start_wfc` -> `init_wfc`
12) `start_charge` -> `init_chg`
13) `set_vel` -> `init_vel`
14) `out_wf` -> `out_wfc_pw`
15) `out_lowf` -> `out_wfc_lcao`
16) `out_wf_r` -> `out_wfc_r`
17) `out_charge` -> `out_chg`
18) `out_potential` -> `out_pot`
19) `mulliken` -> `out_mul`
20) `out_hs` -> `out_mat_hs`
21) `out_hs2` -> `out_mat_hs2`
22) `out_r_matrix` -> `out_mat_r`
23) `charge_extrap` -> `chg_extrap`
24) `move_method` -> `relax_method`
25) `cg_threshold` -> `relax_cg_thr`
26) `force` -> `cal_force`
27) `nstep` -> `relax_nstep`
28) `force_set` -> `out_force`
29) `stress` -> `cal_stress`
30) `trust_radius_max` -> `bfgs_rmax`
31) `trust_radius_min` -> `bfgs_rmin`
32) `trust_radius_ini` -> `bfgs_init`

### CODE REVIEW

**Review by mohanchen — APPROVED** [review]
I am OK with these changes.

**Comment by maki49** [comment]
The test case `604_NO_deepks_ut_H2O_multik` failed. I've run it (build/source/module_deepks/test/test_deepks) on my workstation but it got no output, so I have no idea how to debug it.... @wenfei-li

**Comment by YuLiu98** [comment]
> The test case `604_NO_deepks_ut_H2O_multik` failed. I've run it (build/source/module_deepks/test/test_deepks) on my workstation but it got no output, so I have no idea how to debug it.... @wenfei-li

I reran the tests, and it seems OK now.

**Comment by wenfei-li** [comment]
I have a few comments on the new variable names. The comments are more out of curiosity. If there are some reasons that I don't know of for having the names as they are right now, I would gladly accept the changes:

1. regarding the variable name pw_kpar. It seems to be referring to the partition of k points for parallel calculations. This partition is also relevant for LCAO calculations. Would it be better not to have the 'pw_' prefix?
2. there are 3 variables designating different types of thresholds : diag_thr_e, scf_thr, and relax_cg_thr. It seems that the three variables have different naming conventions. Are we considering being more consistent and name them XX_thr_XX, like diag_thr_e, scf_thr_rho, relax_thr_cg, etc? This would also help if later we want to have something like scf_thr_etot, relax_thr_force, etc.
3. for the init_XX variables, 'init' is often used as a verb, just like in our codes many subroutines have 'init' in their names, suggesting they are used to initialize some class/data structure. I think here it is used as an abbreviation of 'initial', so maybe we can just use 'initial' instead?
4. both scf_nmax and relax_nstep are used to designate the maximum steps allowed for a certain iterative process, but one is called 'nmax' while the other 'nstep'. Would it be better to make them more consistent?
5. since bfgs is used in relaxation, and it seems lots of variables related to relaxation have prefix 'relax_', maybe bfgs_XX could be named relax_bfgx_XX?

**Comment by YuLiu98** [comment]
> I have a few comments on the new variable names. The comments are more out of curiosity. If there are some reasons that I don't know of for having the names as they are right now, I would gladly accept the changes:
> 
> 1. regarding the variable name pw_kpar. It seems to be referring to the partition of k points for parallel calculations. This partition is also relevant for LCAO calculations. Would it be better not to have the 'pw_' prefix?
> 2. there are 3 variables designating different types of thresholds : diag_thr_e, scf_thr, and relax_cg_thr. It seems that the three variables have different naming conventions. Are we considering being more consistent and name them XX_thr_XX, like diag_thr_e, scf_thr_rho, relax_thr_cg, etc? This would also help if later we want to have something like scf_thr_etot, relax_thr_force, etc.
> 3. for the init_XX variables, 'init' is often used as a verb, just like in our codes many subroutines have 'init' in their names, suggesting they are used to initialize some class/data structure. I think here it is used as an abbreviation of 'initial', so maybe we can just use 'initial' instead?
> 4. both scf_nmax and relax_nstep are used to designate the maximum steps allowed for a certain iterative process, but one is called 'nmax' while the other 'nstep'. Would it be better to make them more consistent?
> 5. since bfgs is used in relaxation, and it seems lots of variables related to relaxation have prefix 'relax_', maybe bfgs_XX could be named relax_bfgx_XX?

Thank you for your useful comments! I agree with you except for three below points:
1. I am not sure whether `pw_kpar` is only used in PW calculations or both of PW and LCAO. 
2. `relax_cg_thr` means the threshold of cg method, however, `diag_thr_e` means that energy is taken as the convergence criteria of diagonalization. The two formats have different meanings.
3. The full 'initial' prefix and relax_bfgs_XX formats are slightly long.

Of course, these three points are my own opinion. If @mohanchen has no more comments, I would like to change the names of the above variables as you suggest.

**Comment by YuLiu98** [comment]
I updated some parameters again:
1. `pw_kpar` -> `kpar`
2. `scf_thr` -> `scf_thr_rho`
3. `relax_cg_thr` -> `relax_cg_thr_e`
4. `relax_nstep` -> `relax_nmax`
5. `bfgs_rmax` -> `relax_bfgs_rmax`
6. `bfgs_rmin` -> `relax_bfgs_rmin`
7. `bfgs_init` -> `relax_bfgs_init`
8. `bfgs_w1` -> `relax_bfgs_w1`
9. `bfgs_w2` -> `relax_bfgs_w2`

**Review by wenfei-li — APPROVED** [review]

**Review by dyzheng — APPROVED** [review]

**Comment by wenfei-li** [comment]
> I updated some parameters again:
> 
> 1. `pw_kpar` -> `kpar`
> 2. `scf_thr` -> `scf_thr_rho`
> 3. `relax_cg_thr` -> `relax_cg_thr_e`
> 4. `relax_nstep` -> `relax_nmax`
> 5. `bfgs_rmax` -> `relax_bfgs_rmax`
> 6. `bfgs_rmin` -> `relax_bfgs_rmin`
> 7. `bfgs_init` -> `relax_bfgs_init`
> 8. `bfgs_w1` -> `relax_bfgs_w1`
> 9. `bfgs_w2` -> `relax_bfgs_w2`

looks good to me ~

**Pull request merged**
