### PR TITLE
Style: format CMakeLists.txt using `cmake_format`

### PR DESCRIPTION
**Pull request by caic99**
### Reminder
- [ ] Have you linked an issue with this pull request?
- [ ] Have you added adequate unit tests and/or case tests for your pull request?
- [ ] Have you noticed possible changes of behavior below or in the linked issue?
- [ ] Have you explained the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi? (ignore if not applicable)

### Linked Issue
Fix #...

### Unit Tests and/or Case Tests for my changes
- A unit test is added for each new feature or bug fix.

### What's changed?
This PR only formats the file.

### Any changes of core modules? (ignore if not applicable)
- Example: I have added a new virtual function in the esolver base class in order to ...

### CODE REVIEW

**Comment by haozhihan** [comment]
Why only format the outermost CMakeLists file? There are still many CMakeLists files in the source folder.

**Comment by caic99** [comment]
> Why only format the outermost CMakeLists file? There are still many CMakeLists files in the source folder.

Other CMakeLists files are less complicated.

**Comment by haozhihan** [comment]
According to [Commit message guidelines](https://abacus.deepmodeling.com/en/latest/CONTRIBUTING.html#commit-message-guidelines), I think using keyword `Style` might be more appropriate.

**Review by WHUweiqingzhou — APPROVED** [review]
LGTM.

**Pull request merged**
