### PR TITLE
Test(precision): add the real gaunt function machine precision test .

### PR DESCRIPTION
**Pull request by grysgreat**
Test in the same way as in python-sympy lib. Where gaunt.txt is the test point result set of the gaunt function in sympy. 
And modified the gaunt function property in real_gaunt_table.h (from private to public). 
--issue #3016

### CODE REVIEW

**Review by jinzx10 — CHANGES_REQUESTED** [review]
Could you perform some more checks with higher angular momentum (say, up to l1=l2=8 & l3=16) ? As mentioned in the comment, the current algorithm uses the Racah formula, which consisits of sums of alternating signs and might suffer from numerical issue.

**Comment by grysgreat** [comment]
> Could you perform some more checks with higher angular momentum (say, up to l1=l2=8 & l3=16) ? As mentioned in the comment, the current algorithm uses the Racah formula, which consisits of sums of alternating signs and might suffer from numerical issue.

Sure, how high does (l1,l2,l3) have to be? Is up to(l1=l2=1\~10,l3=0\~24) enough for the test?

**Comment by jinzx10** [comment]
> > Could you perform some more checks with higher angular momentum (say, up to l1=l2=8 & l3=16) ? As mentioned in the comment, the current algorithm uses the Racah formula, which consisits of sums of alternating signs and might suffer from numerical issue.
> 
> Sure, how high does (l1,l2,l3) have to be? Is up to(l1=l2=1~10,l3=0~24) enough for the test?

yeah that would be great!

By the way, the number of coefficients grows very quickly as angular momentum increases. The file that contains the reference values might be pretty big for large l. To keep our repository slim, I think you might take advantage of the symmetries of Gaunt coefficients (see code comment) and break the test into 2 steps. The first step compares our home-made gaunt values with those reference values for symmetry-reduced cases, and the second steps checks whether our home-made gaunt satisfies those symmetries. 

Take your current gaunt.txt as an example. (0 1 1 0 0 0) and (1 0 1 0 0 0) must equal according to the permutation symmetry. So do (0 2 2 0 0 0) and (2 2 0 0 0 0). Gaunt coefficients are also invariant if you flip the signs of all m's. Therefore, (0 2 2 0 -2 2) and (0 2 2 0 2 -2) must equal. You could save more space if you combine those two symmetries, e.g., (1 1 2 -1 -1 2) = (1 1 2 1 1 -2)=(1 2 1 1 -2 1). 

PS: using binary instead of txt is also fine. Hopefully the reference file wouldn't be too big!
PPS: there's also the triangle rule which guarantees that the coefficient is zero if l1+l2<l3.

**Comment by grysgreat** [comment]
> yeah that would be great!
> 
> By the way, the number of coefficients grows very quickly as angular momentum increases. The file that contains the reference values might be pretty big for large l. To keep our repository slim, I think you might take advantage of the symmetries of Gaunt coefficients (see code comment) and break the test into 2 steps. The first step compares our home-made gaunt values with those reference values for symmetry-reduced cases, and the second steps checks whether our home-made gaunt satisfies those symmetries.
> 
> Take your current gaunt.txt as an example. (0 1 1 0 0 0) and (1 0 1 0 0 0) must equal according to the permutation symmetry. So do (0 2 2 0 0 0) and (2 2 0 0 0 0). Gaunt coefficients are also invariant if you flip the signs of all m's. Therefore, (0 2 2 0 -2 2) and (0 2 2 0 2 -2) must equal. You could save more space if you combine those two symmetries, e.g., (1 1 2 -1 -1 2) = (1 1 2 1 1 -2)=(1 2 1 1 -2 1).
> 
> PS: using binary instead of txt is also fine. Hopefully the reference file wouldn't be too big! PPS: there's also the triangle rule which guarantees that the coefficient is zero if l1+l2<l3.

Ok, I'll use these features to add a larger range of test code. By the way, using binary format files does not save much memory space (due to the input is all numbers, the space saving is very small, 238kb->228kb)

**Comment by jinzx10** [comment]
> > yeah that would be great!
> > By the way, the number of coefficients grows very quickly as angular momentum increases. The file that contains the reference values might be pretty big for large l. To keep our repository slim, I think you might take advantage of the symmetries of Gaunt coefficients (see code comment) and break the test into 2 steps. The first step compares our home-made gaunt values with those reference values for symmetry-reduced cases, and the second steps checks whether our home-made gaunt satisfies those symmetries.
> > Take your current gaunt.txt as an example. (0 1 1 0 0 0) and (1 0 1 0 0 0) must equal according to the permutation symmetry. So do (0 2 2 0 0 0) and (2 2 0 0 0 0). Gaunt coefficients are also invariant if you flip the signs of all m's. Therefore, (0 2 2 0 -2 2) and (0 2 2 0 2 -2) must equal. You could save more space if you combine those two symmetries, e.g., (1 1 2 -1 -1 2) = (1 1 2 1 1 -2)=(1 2 1 1 -2 1).
> > PS: using binary instead of txt is also fine. Hopefully the reference file wouldn't be too big! PPS: there's also the triangle rule which guarantees that the coefficient is zero if l1+l2<l3.
> 
> Ok, I'll use these features to add a larger range of test code. By the way, using binary format files does not save much memory space (due to the input is all numbers, the space saving is very small, 238kb->228kb)

oh I forgot that there're a lot of small ints. You are right, maybe txt is fine (or maybe using short instead of int? it's your call)

**Comment by dyzheng** [comment]
If the PR is ready for review, you can ask jinzx to review again.

**Review by jinzx10 — COMMENTED** [review]
what's the purpose of gaunt_symmetry? Its values are set but not used.

**Comment by grysgreat** [comment]
> what's the purpose of gaunt_symmetry? Its values are set but not used.

Oh, this is a temporary variable used to check whether the value points omitted by the gaunt function due to symmetry are correct. I forgot to write the follow-up test part in the last submission, which has just been added.

**Review by jinzx10 — APPROVED** [review]

**Review by dyzheng — APPROVED** [review]

**Pull request merged**
