### PR TITLE
Feature: including the Slater screening to more accurately estimate the hydrogen radial function

### LINKED ISSUE #3632: Feature: extended support on arbitrary atom symbols defined in STRU to calculate QO_OVLP data
### Background

I find present version of qo analysis cannot work for example/smearing/lcao_fe case, because it is AFM system and there are two species defined for Fe in ATOMIC_SPECIES section, Fe1 and Fe2.

### Describe the solution you'd like

To support this, I change to fetch atom symbol from pseudopotential (Atom::pseudo_nc::pseudo::psd) instead of the Atom::label, because the element symbol in pseudopotential will not be changed by user.

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Notice Possible Changes of Behavior (Reminder only for developers)

_No response_

### Notice any changes of core modules (Reminder only for developers)

_No response_

### Notice Possible Changes of Core Modules (Reminder only for developers)

_No response_

### Additional Context

_No response_

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

### LINKED ISSUE #3650: Feature: more accurately estimate the hydrogen-like radial function by including Slater screening
### Background

Present calculation shows there are non-negligible difference between the valence orbital calculated by hydrogen-like radial and numerical atomic orbital. However the hydrogen-like orbital itself is from a single-electron Schrodinger equation, which means it might be less physical than expected.

### Describe the solution you'd like

Simply use Slater screening to mimic the many-electron effect such as nuclear charge screening and repulsion-exchange between electrons.

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Notice Possible Changes of Behavior (Reminder only for developers)

_No response_

### Notice any changes of core modules (Reminder only for developers)

_No response_

### Notice Possible Changes of Core Modules (Reminder only for developers)

_No response_

### Additional Context

_No response_

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

### PR DESCRIPTION
**Pull request by kirk0830**
## Motivation
Originates from result of overlap calculation between primitive hydrogen-like orbital and ABACUS numerical atomic orbitals, the correspondance seems not straightforward as expected, for example the H2O molecule:
image
, in which non-negligible overlap exists between hydrogen-like O 2p orbital and the first and the second p numerical orbital.

However, it may result from the fact the hydrogen-like orbital is solved from single-electron Schrodinger equation instead of many-electron one, therefore, for more objectively estimate the physical meaning of numerical orbital, a simple and feasible candidate would be use Slater screening/shielding coefficient to mimic some of many-electron behavior, such as, electrons in outer shell feel screened nuclear charge instead of the full one, or electrons repulsion will raise the energy and make the orbital extend wider.

## Background: about Slater screening
Originally the single-electron Schrodinger equation reads like:
$\left(-\frac{1}{2}\nabla^2-\frac{Z}{|\mathbf{r}-\mathbf{R}|}\right)\psi \left(\mathbf{r}\right) =E\psi\left(\mathbf{r}\right)$
, however when nuclear charge is high, say for Cu it is 29 and Fe, 26, there will be a rather strong confinement effect act on the electron, which is unphysical. In ionization energy view, hydrogen-like wavefunction cannot predict reasonable value at all.
Slater proposed a simple way to model the many-electron behavior in framework of hydrogen-like orbital: imagine the nuclear charge would be screened partially by inner shell electrons, thus the electrostatic field felt by outer shell electrons will not be so strong as predicted by primary hydrogen-like model. The other aspect is including the repulsion between electrons, this will drive electrons' distribution spread more "outside".  
Quantitively, Slater used an empirical strategy to introduce different screening effect for different electrons in subshells. More specifically:  
- For electrons in (n-2) shell: each electron screens 1.00e nuclear charge
- For electrons in (n-1) shell: for s and p electrons, screens 0.85e, for d and f, screens 1.00e due to they are more localized compared with s and p.
- For electrons in n shell: means in the same subshell, screens 0.35e

With this rule, one can quicky calculate the nuclear charge after screened, say for F the 2p electron, there are 1s2, 2s2, 2p5-1 electrons "inside", therefore, 2p electron will feel the electrostatic field induced by nuclear charge of 9-2*0.85-(2+4)*0.35 = 5.2e instead of 9.0e.  
Correspondingly there will be a small (really small) modification in single-electron Schrodinger equation:  
$\left(-\frac{1}{2}\nabla^2-\frac{Z-\sigma}{|\mathbf{r}-\mathbf{R}|} \right)\psi \left(\mathbf{r}\right) =E\psi\left(\mathbf{r} \right)$
, in which $\sigma$ is the accumulated screening charge.  

## What's changed
Add support of Slater screening by reuse the keyword `qo_screening_coeff`, when it is specified in `qo_basis hydrogen` case, Slater screening will be switched on, otherwise not.

## Result preview
With Slater screening, the H2O case overlap would be:
image
. The overlap between O2p hydrogen-like orbital and p-numerical atomic orbital indeed increases.
A more complex case would be Fe2 system:
image
The behavior of p-numerical atomic orbital seems more similar to many-electron-like, which is consistent with water molecule case.

### CODE REVIEW

**Comment by jinzx10** [comment]
It looks like this PR does much more than what the OP mentions. Apart from fixing issue #3632 by supporting atomic labels like Fe1, Fe2, much of this PR is actually working on the Slater screening. 

I think this PR indeed solves issue #3632, but I'm not able to review the screening stuff as I lack the relevant background information. @WHUweiqingzhou @kirk0830 

(maybe this PR can be splitted into 2, one linked to #3632 , and the other linked to some issue that explains the Slater screening)

**Comment by WHUweiqingzhou** [comment]
@kirk0830,
Maybe you can share the relevant background to us.

**Comment by kirk0830** [comment]
> @kirk0830, Maybe you can share the relevant background to us.

Hi, I have added a small background in Comment section.

**Review by jinzx10 — APPROVED** [review]

**Review by WHUweiqingzhou — APPROVED** [review]
LGTM. Thanks for your effort!

**Pull request merged**
