### PR TITLE
Merge LCAO-refactor into develop 

### PR DESCRIPTION
**Pull request by maki49**
- Refactor  `ESolver_KS_LCAO`: see #891 for details.
- Feature: implement multi-k envelope function. See #808 for details.

### CODE REVIEW

**Comment by maki49** [comment]
DeePKS `NO` cases failed after I pulled develop. 
A segment fault occured in `Gint::gamma_force_new`.

**Comment by dyzheng** [comment]
Pull wenfei's new PR in develop branch and try again?@maki49

**Comment by maki49** [comment]
> Pull wenfei's new PR in develop branch and try again?@maki49

I pulled develop branch and there are some new problems: 
- `311_NO_GO_elec_minus` failed on CI but passed on my workstation;
- `603_NO_deepks_SiO2_bandgap_multik` stopped in `LOC.cal_dm` function because "assertion wg.nr == GlobalC::kv.nks' failed", where nks=64 but wg.nr=1. Maybe some different implementation of `cal_dm` is needed for deepks bandgap label ?

**Comment by dyzheng** [comment]
> > Pull wenfei's new PR in develop branch and try again?@maki49
> 
> I pulled develop branch and there are some new problems:
> 
> * `311_NO_GO_elec_minus` failed on CI but passed on my workstation;
> * `603_NO_deepks_SiO2_bandgap_multik` stopped in `LOC.cal_dm` function because "assertion wg.nr == GlobalC::kv.nks' failed", where nks=64 but wg.nr=1. Maybe some different implementation of `cal_dm` is needed for deepks bandgap label ?

311* case failed is related with #886 , it is only occured in GNU compiler, be correct in Intel compiler.
603* case maybe @wenfei-li can help?

**Comment by maki49** [comment]
The problem in case 603 was because that I didn't add the newest modification of  in ELEC_scf.cpp (#884) into ESolver. Now  it has been resolved.

**Review by dyzheng — APPROVED** [review]

**Pull request merged**
