### PR TITLE
Merge planewave to develop

### PR DESCRIPTION
**Pull request by Qianruipku**

### CODE REVIEW

**Review by caic99 — DISMISSED** [review]
- Does this module provides CMake building?
- Please refactor tests under GoogleTest framework. @caic99 has submitted his PR #603 regarding it.
- Please remove the redundant part of code (e.g. commented code segments, blank files, empty functions).
- Please format the code. The indentations are inconsistent under some files.
- If possible, would you use `std::vector` instead of `new` and `delete`.

**Review by dyzheng — APPROVED** [review]

**Comment by Qianruipku** [comment]
1. We do not have cmakelist now.
2. Google Test will be added in soon.

**Comment by caic99** [comment]
@dyzheng @Qianruipku Sorry but I'm confused that if there are no modifications on `CMakeLists.txt`s, how does it pass current CI test?
And, is it OK to merge such code with a self-made test, neither under GTest framework, nor added to CI? If this is planned in the following steps, create a issue to keep things in track.

**Comment by Qianruipku** [comment]
Because now pw_module is indenpendent of ABACUS. It means ABACUS do not use any functions of this module now.  
In the future, after we reconstruct the program of SCF, we will merge this module into ABACUS.
I also rewrite the tests under GTest framework recently. But I wonder if I need add CMakeList.txt now, since it is not compiled with ABACUS.

**Pull request merged**
