### PR TITLE
fix: memory leak in grid integral

### LINKED ISSUE #994: Memory leak in MD calculation
## Describe the Bug
In case: tests/integral/220_NO_KP_MD_NVE 
Version v2.2.3
Change parameter "md_nstep 20" and run "/usr/bin/time -v mpirun -np 4 abacus 2>time.log |tee log" and check file time.log for number after word "Maximum resident set size". 
The maximum memory number continuously increase when md steps increase.

### PR DESCRIPTION
**Pull request by YuLiu98**
fix #994

### CODE REVIEW

**Review by caic99 — APPROVED** [review]

**Comment by caic99** [comment]
It seems that this PR introduce changes to some function calls. @wenfei-li Would you review this PR before merge?

**Comment by wenfei-li** [comment]
some of the changes seems unnecessary. I'll see which ones are necessary and put then in the code

**Comment by wenfei-li** [comment]
also it seems you are using an old version of the code ...

**Comment by YuLiu98** [comment]
> also it seems you are using an old version of the code ...

I know the grid code in src_lcao is useless, but I change these codes for consistence.

Besides, I have pulled the newest code on the develop branch before PR. Or which one branch is the newest version?

**Pull request closed without merging**
