### PR TITLE
Test: change workflows related to intel image to fix the CI errors.

### PR DESCRIPTION
**Pull request by dyzheng**
### Reminder
- [ ] Have you linked an issue with this pull request?
- [ ] Have you noticed possible changes of behavior below or in the linked issue?
- [ ] Have you explained the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi? (ignore if not applicable)

### Linked Issue
Fix #...

### What's changed?
Disable avx512 and avx2 to make the image in github CI test.

image

### CODE REVIEW

**Review by caic99 — CHANGES_REQUESTED** [review]
Disabling AVX instruction sets affects the performance. Given that ELPA does not support cross-compilation and ABACUS chooses kernel on runtime, I would suggest building containers on self-hosted runners, and keep the default instruction sets.

**Review by caic99 — APPROVED** [review]
This PR fixes the workflow of building containers for latest commit.

**Comment by caic99** [comment]
@dyzheng The building tests is failing. Don't forget to fix them later.

**Comment by dyzheng** [comment]
> @dyzheng The building tests is failing. Don't forget to fix them later.

Thanks for your help.

**Pull request merged**
