### PR TITLE
Fix: out_dm1

### PR DESCRIPTION
**Pull request by wenfei-li**
it seems to be correct now, but there will be some more testing before we make a public release of the functionality

### CODE REVIEW

**Review by dyzheng — APPROVED** [review]
Please commit your new code from a new branch, but not your last PR branch. 
Next time definitely!

**Comment by caic99** [comment]
> Please commit your new code from a new branch, but not your last PR branch. Next time definition!

@wenfei-li And also strip your space between "Fix" and ":", next time perhaps ;-)

**Comment by wenfei-li** [comment]
> > Please commit your new code from a new branch, but not your last PR branch. Next time definition!
> 
> @wenfei-li And also strip your space between "Fix" and ":", next time perhaps ;-)

This time ~

**Comment by wenfei-li** [comment]
> > Please commit your new code from a new branch, but not your last PR branch. Next time definition!
> 
> @wenfei-li And also strip your space between "Fix" and ":", next time perhaps ;-)

:D

**Comment by wenfei-li** [comment]
> Please commit your new code from a new branch, but not your last PR branch. Next time definitely!

:D

**Pull request merged**
