### PR TITLE
Refactor: refactor `psi::memory` namespace and add `module_device` in `module_base`

### LINKED ISSUE #4095: Move the common code about Heterogeneous Computing from `module_psi` to `module_base`
### Describe the Code Quality Issue

We can see that the code in `module_psi/kernel` folder is about common settings for heterogeneous computing. Not just for psi, but for all heterogeneous computing codes. 

Therefore, we should put it at a lower level of architecture in abacus.

### Additional Context

_No response_

### Task list for Issue attackers (only for developers)

- [X] Identify the specific code file or section with the code quality issue.
- [X] Investigate the issue and determine the root cause.
- [X] Research best practices and potential solutions for the identified issue.
- [X] Refactor the code to improve code quality, following the suggested solution.
- [X] Ensure the refactored code adheres to the project's coding standards.
- [X] Test the refactored code to ensure it functions as expected.
- [X] Update any relevant documentation, if necessary.
- [X] Submit a pull request with the refactored code and a description of the changes made.

### PR DESCRIPTION
**Pull request by haozhihan**
### Reminder
- [x] Have you linked an issue with this pull request?
- [x] Have you added adequate unit tests and/or case tests for your pull request?

### Linked Issue
Close #4095 

### Details
* We have noticed that the current code for heterogeneous computing heavily relies on the device and memory related functions under the `module_psi/kernel/` folder. 
* But these functions have gradually begun to serve the heterogeneous computing code of various parts in the entire Abacus software.

Therefore, the naming of the namespaces in `module_psi/kernel/` code is no longer reasonable, the dependency relationships between modules are no longer reasonable, and the storage location is even more unreasonable.

Based on the above situation, I have refactored the code related heterogeneous computing in `module_psi/kernel/`.

### CODE REVIEW

**Comment by mohanchen** [comment]
device

**Comment by mohanchen** [comment]
device

**Comment by denghuilu** [comment]
LGTM! However, I find the namespace `base_device` a bit confusing since it's not a common convention. I've never seen a namespace used like this before. Would it be possible to use `ModuleBase::device` instead? I believe it would be more straightforward and easier to understand where the related codes come from.

**Review by denghuilu — APPROVED** [review]

**Review by mohanchen — APPROVED** [review]

**Comment by caic99** [comment]
@haozhihan Does the codes under `source/module_psi/kernels` is still required? If not so, please remove those files instead of commenting them out.

**Pull request merged**
