### PR TITLE
Tools: support molden file generation from ABACUS LCAO calculation via NAO2GTO

### LINKED ISSUE #3150: Can ABACUS support ELF output?
### Background

Electron localization functions (ELF) can be understood as a measure of the effect of the Pauli repulsion and used to do chemical bond analysis. ELF has values between 0 and 1, where 1 corresponds to perfect localization.

### Describe the solution you'd like

Only the charge density, density gradient and kinetic energy density are needed. The output file format is cube.

image

Ref1: https://www.nature.com/articles/371683a0.pdf
Ref2: https://www.lct.jussieu.fr/pagesperso/contrera/zcam2021/Chembondlab-ZCAM2021.pdf

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Notice Possible Changes of Behavior (Reminder only for developers)

_No response_

### Notice any changes of core modules (Reminder only for developers)

_No response_

### Notice Possible Changes of Core Modules (Reminder only for developers)

_No response_

### Additional Context

_No response_

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

### PR DESCRIPTION
**Pull request by kirk0830**
### Linked Issue
Partially Fix #3150 
In the following I use water molecule as an example. The MO shows similar symmetry with what calculated by CP2K, while the sign is not identical.

### Molecular orbitals postprocessed by Multiwfn and plot by VESTA
ABACUS-CP2K-occ

### Electronic Localized Function (ELF) postprocessed by Multiwfn and plot by VESTA
ABACUS-CP2K-ELF

### CODE REVIEW

**Review by mohanchen — APPROVED** [review]

**Comment by sunliang98** [comment]
Hi, could you please send me the example and the output files from CP2K? I would like to verify the correctness of the ELF obtained using ABACUS. @kirk0830

**Comment by kirk0830** [comment]
> Hi, could you please send me the example and the output files from CP2K? I would like to verify the correctness of the ELF obtained using ABACUS. @kirk0830

@sunliang98 hi, you can simply run 
```bash
mv water.txt water.inp
cp2k.psmp -i water.inp -o water.out
```
with the fo
[water.txt](https://github.com/user-attachments/files/17072008/water.txt)
llowing input
to generate ELF cube. Contact me if meet any problem.

**Comment by sunliang98** [comment]
> > Hi, could you please send me the example and the output files from CP2K? I would like to verify the correctness of the ELF obtained using ABACUS. @kirk0830
> 
> @sunliang98 hi, you can simply run
> 
> ```shell
> mv water.txt water.inp
> cp2k.psmp -i water.inp -o water.out
> ```
> 
> with the fo [water.txt](https://github.com/user-attachments/files/17072008/water.txt) llowing input to generate ELF cube. Contact me if meet any problem.

Thank you. Could you also send me the files from ABACUS, please?

**Comment by kirk0830** [comment]
> > > Hi, could you please send me the example and the output files from CP2K? I would like to verify the correctness of the ELF obtained using ABACUS. @kirk0830
> > 
> > 
> > @sunliang98 hi, you can simply run
> > ```shell
> > mv water.txt water.inp
> > cp2k.psmp -i water.inp -o water.out
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > with the fo [water.txt](https://github.com/user-attachments/files/17072008/water.txt) llowing input to generate ELF cube. Contact me if meet any problem.
> 
> Thank you. Could you also send me the files from ABACUS, please?

@sunliang98 do you mean the elf cube generated by ABACUS? You can run in /tools/molden/water, run
```
python3 molden.py --help
```
to see input description, run
```
python3 molden.py -f water
```
after running ABACUS in folder water/ to generate a molden file, then use Multiwfn to calculate the ELF (), then export as Gaussian cube. You can find the molden and stored cube files here:
[ELF.zip](https://github.com/user-attachments/files/17074031/ELF.zip)

**Pull request merged**
