### PR TITLE
Fix: standalone FindBLAS.cmake, mislink to global-visible lib

### LINKED ISSUE #3589: Misfinding ELPA Headers from Globle Visible Directory
### Describe the bug

If ELPA is installed in any global visible directory and another ELPA(without simbolic link made) was specified through only `ELPA_DIR` or `CMAKE_PREFIX_PATH`, wrong elpa headers from the global visible one would be used. 
That may cause link error for using non-exist symbol, if the header's version mismatch with the library. A typical situation is, one personal user installed libelpa-dev from apt, and providing a install from source with version newer than 2022.11.001. 

### Expected behavior

CMake should catch the command-line earlier than the global one.

### To Reproduce

1. Make a old elpa include available in a global visible directory. It should have `ELPA_API_VERSION < 20220501`  as `source/module_hsolver/genelpa/elpa_generic.hpp` defined.
         e. g. install `libelpa-dev` from apt and `/usr/include/elpa/elpa/elpa.h` appears, with a version of `2021.11.001`.
2. Try compile abacus with another new elpa. It should have `ELPA_API_VERSION >= 20220501`.
        e. g. `cmake -DELPA_DIR=/home/yizeyi18/soft/elpa-2023.05.001-install`
3. At link time, `ld` would throw a error saying symbol not found.

### Environment

- OS: Ubuntu 22.04
- Compiler: gcc 13.2.0
- Dependencies: ELPA

### Additional Context

Previously, ABACUS find ELPA headers through trying to find `$DIR/include/elpa/elpa.h` or  `$DIR/include/elpa/elpa/elpa.h` for `$DIR` in `CMAKE_PREFIX_PATH`, `ELPA_DIR` then global visible dirs. For users manually made the simbolic link `$ELPA_DIR/include/elpa-$VERSION -> $ELPA_DIR/include/elpa` following the docs, this would work; if not, error occcurs. 
#3478 changed the doc, provided another routine to find them, but made the old routine done first; if a user is lucky enough to both install ELPA from apt and source, this bug will encounter. 

Currently define `ELPA_INCLUDE_DIRS` in the command line explicitly is a way to avoid this bug; a PR would fix this later.

### Task list for Issue attackers (only for developers)

- [X] Verify the issue is not a duplicate.
- [X] Describe the bug.
- [X] Steps to reproduce.
- [X] Expected behavior.
- [X] Error message.
- [X] Environment details.
- [X] Additional context.
- [X] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [X] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

### PR DESCRIPTION
**Pull request by yizeyi18**
### Reminder
- [x] Have you linked an issue with this pull request?
- [x] Have you noticed possible changes of behavior below or in the linked issue?
- [ ] Have you explained the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi? (ignore if not applicable)

### Linked Issue
Fix #3589, https://github.com/deepmodeling/abacus-develop/issues/3497#issuecomment-1924913394

### What's changed?
- Added a check for include dir in FindELPA.cmake, to avoid using unspecified global visible header
- Changed LibXC finding strategy to pkg-config first, to avoid linking to unspecified global visible lib
- Made a standalone FindBLAS.cmake, removed incompatible blas in FindLAPACK.cmake

### Any changes of core modules? (ignore if not applicable)
- No.

### CODE REVIEW

**Comment by caic99** [comment]
Hi @yizeyi18 ,
I wonder whether the name `FindBLAS` conflicts with the [standard interface](https://cmake.org/cmake/help/latest/module/FindBLAS.html) by CMake? And, is it possible to use that interface? Thanks!

**Comment by yizeyi18** [comment]
> Hi @yizeyi18 , I wonder whether the name `FindBLAS` conflicts with the [standard interface](https://cmake.org/cmake/help/latest/module/FindBLAS.html) by CMake? And, is it possible to use that interface? Thanks!

There is certainly conflict between cmake and abacus-builtin FindBLAS as well as FindLAPACK, and the builtin one would be executed. I 'm happy to try the cmake one, although I had not used it——a bunch of open source quantum chem package, e. g. CP2K, ScalES, Dalton, use their own FindBLAS/LAPACK/ScaLAPACK/math, I had no idea why.

**Comment by caic99** [comment]
> There is certainly conflict between cmake and abacus-builtin FindBLAS as well as FindLAPACK, and the builtin one would be executed. I 'm happy to try the cmake one, although I had not used it

Hi @yizeyi18 ,
I think it's OK to use our own config with a different name.

> a bunch of open source quantum chem package, e. g. CP2K, ScalES, Dalton, use their own FindBLAS/LAPACK/ScaLAPACK/math, I had no idea why.

It provides certainty and also rooms to tweak, since the user does not always use the latest CMake module files.

**Comment by yizeyi18** [comment]
@caic99 I made a demo using cmake's FindBLAS/FindLAPACK in https://github.com/yizeyi18/abacus-develop/tree/cmake-FindBLAS, may you take a look?
This demo simply deleted the builtin ones and added some variable wrapper, runs on my pc.

**Comment by yizeyi18** [comment]
@caic99 The demo above got merged. 
The intel check failed to init check container, could you help to restart it?

**Review by caic99 — APPROVED** [review]

**Comment by scott-5** [comment]
hi, when I was compiling ABACUS v3.5.4 with option `-DLibxc_DIR=~/libxc`, it occurs an error message:
```
-- Checking for one of the modules 'libxc'
CMake Error at /home/user/miniconda3/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Libxc (missing: Libxc_LINK_LIBRARIES Libxc_INCLUDE_DIRS)
Call Stack (most recent call first):
  /home/user/miniconda3/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLibxc.cmake:14 (find_package_handle_standard_args)
  CMakeLists.txt:549 (find_package)
-- Configuring incomplete, errors occurred! 
```
I try to provide `-DLibxc_LINK_LIBRARIES=~/libxc/lib` and `Libxc_INCLUDE_DIRS=~/libxc/include`, other error is that:
```
-- Checking for one of the modules 'libxc'
-- Found Libxc: ~/libxc/lib  
-- Found Libxc: version 
CMake Error at CMakeLists.txt:551 (if):
  if given arguments:
    "VERSION_LESS" "5.1.7"
  Unknown arguments specified
```
Now I don't know how to solve this problem.

**Comment by yizeyi18** [comment]
@scott-5 Hi, may you show the content of `~/libxc/lib/pkgconfig/libxc.pc`? From your provided output, CMake found a pkg-config and failed to get information from pkgconf file.

**Comment by scott-5** [comment]
Of course. 
```
prefix=/home/user/libxc                                                                                                                
exec_prefix=/home/user/libxc
libdir=${exec_prefix}/lib64
includedir=${prefix}/include

Name: libxc
Description: Library of exchange and correlation functionals to be used in DFT codes
Requires:
Version: 6.2.0
Libs: -L${libdir} -lxc
Cflags: -I${includedir}
```
(I made a mistake. In fact, only `~/libxc/lib64` exists and not `~/libxc/lib`. So I change `-DLibxc_LINK_LIBRARIES` to `~/libxc/lib64`. But they get the same error.
```
-- Found Libxc: ~/libxc/lib64  
-- Found Libxc: version 
CMake Error at CMakeLists.txt:551 (if):
  if given arguments:
    "VERSION_LESS" "5.1.7"
  Unknown arguments specified
```)

**Comment by yizeyi18** [comment]
@scott-5 May you try changing `~/libxc` in command line to `${HOME}/libxc` or `/home/user/libxc`? I guess pkg-config may have problem facing non-absolute path.

**Comment by scott-5** [comment]
It works. Thank you. Aha, but it is weird that using `~` for other options(like -DELPA_DIR=~/elpa) can be passed.

**Comment by yizeyi18** [comment]
@scott-5 Ehh, that's a bit software-dependent.
elpa would not have something like `ELPA_config.cmake` in any of its redistribution, that makes it's possible to use some cmake's builtin function as its default routine, and judge if we fall into a wrong global visible dir. CMake function supports `~/` as `$HOME/`.
But Libxc may have `Libxc._config.cmake`; even worse, apt-installed libxc have it. While using cmake's builtin function, a apt-installed libxc would seize in some cases, e. g. using one libxc built with gnu toolchain. In regard of that, pkg-config method was choosed to be default, although it also have some problems.

**Comment by scott-5** [comment]
Got it. Thanks again.

**Pull request merged**
