### PR TITLE
Feature: add plain and pulay mixing for EXX

### LINKED ISSUE #2182: MgO can't converge using HSE
### Describe the bug

I tested MgO with two iteration schemes of HSE and found that no matter which scheme it is difficult to converge
Here is my INPUT file:
```
INPUT_PARAMETERS
# Created by Atomic Simulation Enviroment
calculation                             scf
ecutwfc                                 100
smearing_method                         gaussian
smearing_sigma                          0.01
basis_type                              lcao
ks_solver                               genelpa
mixing_type                             pulay
mixing_beta                             0.7
scf_thr                                 1e-06
out_chg                                 1
exx_pca_threshold                       0.0001
exx_c_threshold                         0.0001
exx_dm_threshold                        0.0001
exx_cauchy_threshold                    1e-07
exx_ccp_rmesh_times                     1.2
exx_separate_loop                       0  #1
ntype                                   2
dft_functional                          hse
```
Here are my output files:

1. for `exx_separate_loop 0`
[single.txt](https://github.com/deepmodeling/abacus-develop/files/11144231/single.txt)
2. for `exx_separate_loop 1`
[double.txt](https://github.com/deepmodeling/abacus-develop/files/11144234/double.txt)

### Expected behavior

_No response_

### To Reproduce

_No response_

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by 1041176461**
Fix #2182
This is the result of running with the modified version
[pulay.txt](https://github.com/deepmodeling/abacus-develop/files/11144279/pulay.txt)

### CODE REVIEW

**Comment by dyzheng** [comment]
Hello, what is the relationship between this PR and #2072 @1041176461

**Comment by 1041176461** [comment]
> Hello, what is the relationship between this PR and #2072 @1041176461

This PR is to add mixng schemes for EXX to solve the convergence problem(https://github.com/deepmodeling/abacus-develop/issues/2182), and that (https://github.com/deepmodeling/abacus-develop/pull/2072) is based on LibRI for further acceleration optimization.

**Comment by dyzheng** [comment]
> > Hello, what is the relationship between this PR and #2072 @1041176461
> 
> This PR is to add mixng schemes for EXX to solve the convergence problem(#2182), and that (#2072) is based on LibRI for further acceleration optimization.

Good job, Mohan Chen will review this code.

**Comment by maki49** [comment]
I've cloned your branch `1041176461:dm_mixing` and run a MgO case.  It got converged.

**Review by mohanchen — APPROVED** [review]

**Review by dyzheng — APPROVED** [review]

**Pull request merged**
