### PR TITLE
对构造函数进行修改，方便对全部变量进行初始化而不是之后再进行

### PR DESCRIPTION
**Pull request by GHSSHG**
### Reminder
- [ ] Have you linked an issue with this pull request?
- [ ] Have you added adequate unit tests and/or case tests for your pull request?
- [ ] Have you noticed possible changes of behavior below or in the linked issue?
- [ ] Have you explained the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi? (ignore if not applicable)

### Linked Issue
Fix #...

### Unit Tests and/or Case Tests for my changes
- A unit test is added for each new feature or bug fix.

### What's changed?
- Example: My changes might affect the performance of the application under certain conditions, and I have tested the impact on various scenarios...

### Any changes of core modules? (ignore if not applicable)
- Example: I have added a new virtual function in the esolver base class in order to ...

### CODE REVIEW

**Review by caic99 — CHANGES_REQUESTED** [review]
Please initialize values in the corresponding .h file, instead of the constructor.

**Review by mohanchen — APPROVED** [review]
LGTM

**Comment by GHSSHG** [comment]
> 请初始化相应的 .h 文件中的值，而不是构造函数。

我想的是构造的时候如果没有就默认初始化，如果有给了的值的话就按给定的值。改.h文件的话就没这么灵活

**Review by mohanchen — APPROVED** [review]
LGTM

**Comment by mohanchen** [comment]
LGTM, I will close it now.

**Pull request closed without merging**
