### PR TITLE
Merge SDFT to develop

### PR DESCRIPTION
**Pull request by Qianruipku**
for issue #914

### CODE REVIEW

**Review by dyzheng — COMMENTED** [review]
Is there any test case for stochastic-DFT calculation related to this PR?

**Comment by Qianruipku** [comment]
Not yet. I will later add force and stress for SDFT. Then I will add test cases.

**Comment by dyzheng** [comment]
> Not yet. I will later add force and stress for SDFT. Then I will add test cases.

I need test cases to ensure my HSolver code won't break the stochastic-DFT functional.

**Comment by Qianruipku** [comment]
Maybe you just need to write HSolver for KSDFT. And I write HSolver_SDFT?

**Comment by Qianruipku** [comment]
Any way, I will add cases as fast as possible.

**Comment by dyzheng** [comment]
Okay, I need to change GlobalC::wf.evc to Psi in whole of the code. I will not change the code of ESolver_SDFT_PW until you finish the tests.

**Comment by Qianruipku** [comment]
okay

**Review by mohanchen — APPROVED** [review]

**Pull request merged**
