### PR TITLE
fix: fix bugs of multi-kpoints for tddft and add autotest

### PR DESCRIPTION
**Pull request by lyb9812**
1. fix bug of multi-kpoints for tddft
2. add autotests of multi-kpoints for tddft
3. fix serial version

### CODE REVIEW

**Review by denghuilu — APPROVED** [review]

**Comment by dyzheng** [comment]
Where are pseudopotential and orbital files from？ 
@lyb9812

**Comment by lyb9812** [comment]
> 



> Where are pseudopotential and orbital files from？
> @lyb9812

Pseudopotential files are from PWmat. Orbital files are generated from these pseudo potential files using ABACUS.

**Comment by dyzheng** [comment]
> > 
> 
> > Where are pseudopotential and orbital files from？
> > @lyb9812
> 
> Pseudopotential files are from PWmat. Orbital files are generated from these pseudo potential files using ABACUS.

@lyb9812 What is the website of these pseudopotential files? can you find the license of this pseudopotential library?

**Comment by lyb9812** [comment]
> 

http://www.pwmat.com/potential-download

**Comment by lyb9812** [comment]
> > > Where are pseudopotential and orbital files from？
> > > @lyb9812
> > 
> > 
> > Pseudopotential files are from PWmat. Orbital files are generated from these pseudo potential files using ABACUS.
> 
> @lyb9812 What is the website of these pseudopotential files? can you find the license of this pseudopotential library?

http://www.pwmat.com/potential-download

**Pull request merged**
