### PR TITLE
update module_md

### PR DESCRIPTION
**Pull request by YuLiu98**
1) fix a bug that the freedom is wrong due to the mass center is fixed;
2) add a new InitVel function to fix the mass center;
3) update some constants in MD.

### CODE REVIEW

**Comment by caic99** [comment]
`tests/integrate/701_LJ_Ar/Restart_md.dat`
Is this large file required?

**Comment by caic99** [comment]
Plus, did you require for other maintainer's review before merging?

**Comment by YuLiu98** [comment]
> `tests/integrate/701_LJ_Ar/Restart_md.dat` Is this large file required?

This file is used to restart MD to ensure every run is the same.
I will test whether it is OK without the file.

**Comment by YuLiu98** [comment]
> Plus, did you require for other maintainer's review before merging?

The PR is allowed by @dyzheng .

**Pull request merged**
