### PR TITLE
Feature: enable `lcao_in_pw` function on present version

### PR DESCRIPTION
**Pull request by kirk0830**
## Changes
- Modify time when initialize pw wavefunction
- Support `float/double/std::complex<float>/std::complex<double>` with `psi::DEVICE_CPU/psi::DEVICE_GPU` feature, in accord with the newest implementation of ESolver_KS_PW

## Calculation result comparison
|case|ref|new implementation|delta E (eV)|
|---|---|---|---|
|401_NP_KP_sp|-712.4253628200150388|-712.4239765233179|0.0013862966|
|401_NP_KP_spd|-211.3197071622673775|-211.3197071630929|0.0000000008|

### CODE REVIEW

**Comment by kirk0830** [comment]
Link to issue #2973

**Comment by kirk0830** [comment]
@dyzheng suggest make lcao_in_pw workflow more individual, especially for branching HSolver and ESolver classes. This draft will exist here for long time.

**Comment by hongriTianqi** [comment]
Fix #2973

**Review by dyzheng — APPROVED** [review]
Thanks for your contribution for recover the feature for LCAO_in_PW SCF calculation.
I hope you can add some documents in on-line documentations for this feature.

**Pull request merged**
