### PR TITLE
Fix: optimize the IO of lcao-wfc and charge

### LINKED ISSUE #2975: Request: Flexibly detect and read wavefunction file as init guess
### Background

In VASP, if WAVECAR file exists ,VASP can automatically read WAVECAR file as guess for wave-function
In ABACUS LCAO calculation ,one can set `out_wfc_lcao 1` and `init_wfc filename` to read wave-function calculation result, but one cannoe let ABACUS automatically read existing `wfc` files , or set `init_wfc file` and switch to atomic guess if this `wfc` files is not exists

This will be very good for ASE-ABACUS calculation like geometry optimization and NEB calculation

### Describe the solution you'd like

One of these solution will do good
1. ABACUS can detect a name of wavefunction file, and automatically read it
2. when `init_wfc` setting to `file`, ABACUS can read wavefunction from `file`, and, if `file` not exist, switch back to atomic guess of wave function

### Additional Context

_No response_

### Task list for Issue attackers

- [X] Review and understand the proposed feature and its importance.
- [X] Research on the existing solutions and relevant research articles/resources.
- [x] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

### PR DESCRIPTION
**Pull request by maki49**
Fix #2975
- read lcao wavefunction only in the initial ion step
- change error-exit to warning and return to atomic initialization in reading lcao wavefunction and charge density
- overwrite rather than append when writing lcao wavefunction

### CODE REVIEW

**Review by QuantumMisaka — COMMENTED** [review]
Thanks! It will fix #2975 and helps a lot

**Comment by QuantumMisaka** [comment]
@maki49 Could the `init_chg` option be similar to `init_wfc` option that : if SPIN*.cube files do not exist and `init_chg file` option specified, raise a warning in stdout/running*log and switch to atomic option?

**Comment by maki49** [comment]
> @maki49 Could the `init_chg` option be similar to `init_wfc` option that : if SPIN*.cube files do not exist and `init_chg file` option specified, raise a warning in stdout/running*log and switch to atomic option?

Done. 
Also, the append-output is changed to overwriting.

**Comment by QuantumMisaka** [comment]
I've directly tested this branch, the lcao-wfc part have no running problem, but when setting `init_chg file` but no SPIN*.cube file, this error will arise:
```
Initial plane wave basis and FFT box
 ---------------------------------------------------------
 DONE(0.206486   SEC) : INIT PLANEWAVE
 -------------------------------------------
 SELF-CONSISTENT : 
 -------------------------------------------
 START CHARGE      : file
 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                         NOTICE                           
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 
 Can't find even an electron!
 CHECK IN FILE : OUT.ABACUS/warning.log
 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                         NOTICE                           
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

may need more refinements.

**Comment by maki49** [comment]
> I've directly tested this branch, the lcao-wfc part have no running problem, but when setting `init_chg file` but no SPIN*.cube file, this error will arise:

I've fixed it, does this problem still exist now?

**Comment by QuantumMisaka** [comment]
> > I've directly tested this branch, the lcao-wfc part have no running problem, but when setting `init_chg file` but no SPIN*.cube file, this error will arise:
> 
> I've fixed it, does this problem still exist now?

Fixed

**Review by QuantumMisaka — APPROVED** [review]
Worked well. 
If wavefunction/charge extrapolation by analysis the new input STRU and old wfc/chg file can be done, the efficiency for outer interface using ABACUS will be improved more. I'll pay some attention on it.

**Comment by QuantumMisaka** [comment]
@kirk0830 Could you review and merge it ?

**Comment by QuantumMisaka** [comment]
The ABACUS directly from this branch have much low efficiency in SCF of ferromagnetic system than ABACUS commit 573b6eadb, but this IO should not have any efficiency change. I'll have more test after merged.

**Comment by QuantumMisaka** [comment]
> The ABACUS directly from this branch have much low efficiency in SCF of ferromagnetic system than ABACUS commit [573b6ea](https://github.com/deepmodeling/abacus-develop/commit/573b6eadbc2d9e2f3466eb177b42310418d99873), but this IO should not have any efficiency change. I'll have more test after merged.

The latest abacus branch have no problem. The performance tests should be done after merged

**Comment by QuantumMisaka** [comment]
> > The ABACUS directly from this branch have much low efficiency in SCF of ferromagnetic system than ABACUS commit [573b6ea](https://github.com/deepmodeling/abacus-develop/commit/573b6eadbc2d9e2f3466eb177b42310418d99873), but this IO should not have any efficiency change. I'll have more test after merged.
> 
> The latest abacus branch have no problem. The performance tests should be done after merged

No problem now

**Comment by hongriTianqi** [comment]
Can `nscf` be done by reading wfc now? Have spin 1, 2, 4 all been considered? @maki49 @QuantumMisaka

**Comment by QuantumMisaka** [comment]
> Can `nscf` be done by reading wfc now? Have spin 1, 2, 4 all been considered? @maki49 @QuantumMisaka

CANNOT

I tried `nscf` calculation with SPIN1.cube and wavefunction file from `scf` calculation, and `nscf` input setting:
```
init_chg        atomic
init_wfc        file
```
from the stdout, the wavefunction file can not be read, `nscf` calculation will still use charge file. The reason is that the KPOINTS is different from `scf` and `nscf`
```
 SPIN    KPOINTS         PROCESSORS  NBASE       
 1       128             4           104         
 ---------------------------------------------------------
 Use Systematically Improvable Atomic bases
 ---------------------------------------------------------
 ELEMENT ORBITALS        NBASE       NATOM       XC          
 Si      2s2p1d-7au      13          8           
 ---------------------------------------------------------
 Initial plane wave basis and FFT box
 ---------------------------------------------------------
 DONE(0.0661723  SEC) : INIT PLANEWAVE
 -------------------------------------------
 NONSELF-CONSISTENT : 
 -------------------------------------------
 Read in wave functions files: 128
 Successfully read in wave functions 1
In k-dependent wave function file, k point is not correct
WARNING: Failed to read in wavefunction, use default initialization instead.
 START CHARGE      : file
 NON-SELF CONSISTENT CALCULATIONS
```

For reading wavefunction and charge file do `scf` calculation, spin 1 and 2 is running normally, spin 4 is not tested, but due to this change only concern IO part, I consider that spin 4 have no problem.

**Review by kirk0830 — APPROVED** [review]

**Comment by hongriTianqi** [comment]
OK, do we need to read wfc and charge together to do scf now in spin 1 and 2? Can we read wfc only?

**Comment by QuantumMisaka** [comment]
> OK, do we need to read wfc and charge together to do scf now in spin 1 and 2? Can we read wfc only?

From my test in nspin=2 calculation, set
```
init_chg        atomic
init_wfc        file
```
and 
```
init_chg        file
init_wfc        file
```
have the SAME effect. the charge file SPIN*.cube will be read in the latter setting, but the `scf` calculation process is the same as the former, I guess the charge density will be initialized by wavefunction whatever charge file is read is not if wavefunction file is read.

**Comment by QuantumMisaka** [comment]
> OK, do we need to read wfc and charge together to do scf now in spin 1 and 2? Can we read wfc only?

As #2975 . read wfc (or charge file) to do scf calculation can make ABACUS more efficient if using interface like ASE to do optimization or NEB calculation. This file can be iteratively read when ASE do each ionic step. 

Of course it is better if wavefunction extrapolation can be done when the STRU of read wfc/charge file in last ionic step and the STRU in this ionic step have some difference.  I'll focus on it later

**Comment by hongriTianqi** [comment]
OK, I have no other questions. Thanks for your reply.

**Comment by hongriTianqi** [comment]
Sorry, by the way, can we do the `nscf` calculation with the same `kpt` file? If so, maybe we can close #1235.

**Comment by QuantumMisaka** [comment]
> Sorry, by the way, can we do the `nscf` calculation with the same `kpt` file? If so, maybe we can close #1235.

in same KPT calculation of `nscf`, the `nscf` will still trying to read and use charge file. and if charge file not exist. the `nscf` process can still be done, but I don't know whether the result is based on read wfc file . working on it

**Comment by QuantumMisaka** [comment]
One warning generated in compile process:
```
/lustre/home/2201110432/apps/abacus/abacus-develop-relax-read/source/module_hamilt_lcao/hamilt_lcaodft/DM_gamma.cpp:81:20: warning: & has lower precedence than ==; == will be evaluated first [-Wparentheses]
    if (istep == 0 & INPUT.init_wfc == "file")
        ~~~~~~~~~~~^
/lustre/home/2201110432/apps/abacus/abacus-develop-relax-read/source/module_hamilt_lcao/hamilt_lcaodft/DM_gamma.cpp:81:20: note: place parentheses around the '==' expression to silence this warning
    if (istep == 0 & INPUT.init_wfc == "file")
                   ^
        (         )
/lustre/home/2201110432/apps/abacus/abacus-develop-relax-read/source/module_hamilt_lcao/hamilt_lcaodft/DM_gamma.cpp:81:20: note: place parentheses around the & expression to evaluate it first
    if (istep == 0 & INPUT.init_wfc == "file")
                   ^
                 (                           )
```
But it seems not a huge problem

**Comment by QuantumMisaka** [comment]
> Sorry, by the way, can we do the `nscf` calculation with the same `kpt` file? If so, maybe we can close #1235.

@hongriTianqi I tested the `nscf` calculation using `wfc` file with same `kpt` file and without charge file, the TDOS and PDOS by `nscf` calculation from `wfc` file and charge file are not exactly the same, but they are much similar.

example: Si bulk with 8 atoms, KPT is `9 9 9`

TDOS below, left from nscf with wfc , right from scf and nscf with charge

image

PDOS below, left from nscf with wfc , right from scf and nscf with charge

image

**Comment by hongriTianqi** [comment]
@QuantumMisaka Thanks. Then ISSUE #1235 is still not solved. We may keep it open.

**Pull request merged**
