### PR TITLE
Perf: optimize function snap_psibeta_half_tddft

### LINKED ISSUE #4664: using velocity gauge is much slower than length gauge in TDDFT
### Details

If I use velocity gauge in TDDFT(td_stype=1), ABACUS is much slower than the length gauge, 
Here is the input and log files I used:
[compareGagus.tar.gz](https://github.com/user-attachments/files/16189176/compareGagus.tar.gz)
Based on the time consumption log, my guess is the bottleneck is in the modules
 `Evolve_elec           evolve_psi ` 
 ` HSolverLCAO           solve` 
` HamiltLCAO          updateHk`

Besides, it seems the 1st electronic step in each ionic step is the most time consuming.
Snipaste_2024-07-12_14-02-46

I wish the developers could help to improve the performance when using velocity gauge.

### Task list for Issue attackers (only for developers)

- [ ] Reproduce the performance issue on a similar system or environment.
- [ ] Identify the specific section of the code causing the performance issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified performance issue.
- [ ] Implement the chosen solution to address the performance issue.
- [ ] Test the implemented solution to ensure it improves performance without introducing new issues.
- [ ] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

### PR DESCRIPTION
**Pull request by dzzz2001**
### Background
`snap_psibeta_half_tddft` is a hotspot function in TDDFT calculations. Through profiling with VTune, we discovered that a significant portion of the time spent in this function is due to `Polynomial_Interpolation` function and the `resize` operation in `rl_sph_harm` functions: 
image
image

The implementation of `Polynomial_Interpolation` was inefficient, with much time spent on unnecessary binary searches. We replaced the original `Polynomial_Interpolation` function in `snap_psibeta_half_tddft` with the `ModuleBase::PolyInt::Polynomial_Interpolation` function from the `ModuleBase` module. After the replacement, the time spent in this function was significantly reduced.

The root cause of the `resize` operation time consumption in the `rl_sph_harm` function was the declaration of vectors inside the loop, leading to frequent allocations and deallocations. By moving the vector declarations outside the loop, we reduced the time spent on these operations. 

After optimization, the time spent in this function was reduced by more than two times.
**Before optimization**:
image
**After optimization**:
image

### Linked Issue
fix #4664

### CODE REVIEW

**Comment by dzzz2001** [comment]
My optimization of TDDFT has reached a conclusion. After this PR and the previous PR #5037, testing the same case on my machine using "OMP_NUM_THREADS=7 mpirun -n 4 abacus", the time spent in the calculate_HR function has decreased from 84% to 20%, resulting in the function computation being accelerated by approximately 20 times. It has now become a less critical hotspot function:
**Before**:
image
**After**:
image

Although there is still room for optimization in the MPI parallelization strategy of the calculate_HR function, the modifications are complex and the potential gains are minimal. Therefore, I do not plan to make further changes at this time.

When computing TDDFT, it is recommended to set a higher number of OpenMP threads and configure the number of MPI processes to be a perfect square, avoiding prime numbers. This setting can reduce the negative effects of the MPI parallelization strategy and achieve better computational efficiency

**Comment by dzzz2001** [comment]
The replacement of the `Polynomial_Interpolation` function has introduced some minor numerical errors:
image
I want to know if these errors are acceptable @ESROAMER . If they are, I will update the test cases.

**Review by ESROAMER — APPROVED** [review]
Impressive optimization! Thanks for your efforts.

**Comment by ESROAMER** [comment]
You may link issue #4664 in this PR.

**Review by mohanchen — APPROVED** [review]

**Pull request merged**
