### PR TITLE
modify the reading of frozen ions and velocities 

### PR DESCRIPTION
**Pull request by lyb9812**
modify the reading of frozen ions and velocities ; add tddft test

### CODE REVIEW

**Comment by caic99** [comment]
> tests/integrate/601_NO_TDDFT_N2/tddft.sh

We may not include the slurm batch file.

**Comment by lyb9812** [comment]
> > tests/integrate/601_NO_TDDFT_N2/tddft.sh
> 
> We may not include the slurm batch file.

sorry, I delete it now

**Comment by caic99** [comment]
Do we need to test 601_* cases by default? @dyzheng 
Also, these new testcases might need documentation in tests/integrate/README.md .

**Comment by caic99** [comment]
And, is the new test case related to #275 ?

**Comment by dyzheng** [comment]
The frozen atom reading method is changed! Please modify your code to keep old STRU format can be read correctly!

**Pull request merged**
