### PR TITLE
add changes for serial version

### PR DESCRIPTION
**Pull request by lyb9812**
1. add #ifdef __MPI in ext related codes
2. add #ifdef __MPI in some other codes

### CODE REVIEW

**Comment by lyb9812** [comment]
Linked issue #709

**Comment by caic99** [comment]
> Linked issue #709

Hi @lyb9812 ,
You may link issues in the right side of PR page.

**Comment by lyb9812** [comment]
> > Linked issue #709
> 
> Hi @lyb9812 , You may link issues in the right side of PR page.

**Comment by lyb9812** [comment]
> > Linked issue #709
> 
> Hi @lyb9812 , You may link issues in the right side of PR page.

I cannot see any button for setting on the right side on my computer.

**Comment by caic99** [comment]
> > > Linked issue #709
> > 
> > 
> > Hi @lyb9812 , You may link issues in the right side of PR page.
> 
> I cannot see any button for setting on the right side on my computer.
截屏2022-02-15 上午10 44 26
FYI
You can also search for a GitHub official doc, see https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue .

**Comment by lyb9812** [comment]
> > > > Linked issue #709
> > > 
> > > 
> > > Hi @lyb9812 , You may link issues in the right side of PR page.
> > 
> > 
> > I cannot see any button for setting on the right side on my computer.
> 
> 截屏2022-02-15 上午10 44 26
> 
> FYI You can also search for a GitHub official doc, see https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue .

[image](https://user-images.githubusercontent.com/88070104/153985334-9e0e2b96-2187-4304-90dc-3eda757aefdc.png)
There is no gear like button and I cannot click Linked issues.

**Comment by caic99** [comment]
> 
> [image](https://user-images.githubusercontent.com/88070104/153985334-9e0e2b96-2187-4304-90dc-3eda757aefdc.png) There is no gear like button and I cannot click Linked issues.

Sorry, I forgot that manually link PR requires write permission to repo. My bad.
However, [Linking a pull request to an issue using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) should work.

**Comment by lyb9812** [comment]
> > [image](https://user-images.githubusercontent.com/88070104/153985334-9e0e2b96-2187-4304-90dc-3eda757aefdc.png) There is no gear like button and I cannot click Linked issues.
> 
> Sorry, I forgot that manually link PR requires write permission to repo. My bad. However, [Linking a pull request to an issue using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) should work.

Ok, thank you.

**Pull request merged**
