### PR TITLE
docs: fix dead link in markdown files

### PR DESCRIPTION
**Pull request by caic99**

### CODE REVIEW

**Comment by caic99** [comment]
@dyzheng There are still some keywords which I can not find
nlHWmuFMMv

**Comment by dyzheng** [comment]
These 6 parameters are in ABACUS but lack of description in docs.

**Comment by dyzheng** [comment]
@YuLiu98 Does ABACUS has parameter : "md_t"?

**Review by dyzheng — APPROVED** [review]

**Comment by YuLiu98** [comment]
> @YuLiu98 Does ABACUS has parameter : "md_t"?

md_t denotes md_tfirst and md_tlast in the original manual.

**Pull request merged**
