### PR TITLE
Fix: cuda build target

### PR DESCRIPTION
**Pull request by caic99**
### Reminder
- [ ] Have you linked an issue with this pull request?
- [ ] Have you noticed possible changes of behavior below or in the linked issue?
- [ ] Have you explained the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi? (ignore if not applicable)

### Linked Issue
https://github.com/conda-forge/abacus-feedstock/pull/16
### What's changed?
- Example: My changes might affect the performance of the application under certain conditions, and I have tested the impact on various scenarios...

### Any changes of core modules? (ignore if not applicable)
- Example: I have added a new virtual function in the esolver base class in order to ...

### CODE REVIEW

**Comment by njzjz** [comment]
Still have the problem; see https://github.com/conda-forge/abacus-feedstock/pull/16#issuecomment-1833271324

**Comment by caic99** [comment]
Can someone help please? @denghuilu @haozhihan

**Comment by njzjz** [comment]
It accepts `6.0` instead of `60`, unlike CMake.

**Comment by caic99** [comment]
> It accepts `6.0` instead of `60`, unlike CMake.

Since the compatibility, I will remove the usage of this var, leaving it to the user.

**Review by haozhihan — APPROVED** [review]

**Pull request merged**
