### PR TITLE
Fix: eliminate compilaton error due to the `#define private public` macro in all unittests

### LINKED ISSUE #4673: Build failed on oneAPI toolchain with deepks and testing ON
### Describe the bug

When building latest abacus with `-DBUILD_TESTING=ON` and `-DENABLE_DEEPKS=1`, compiler error encountered:
img_v3_02cn_0c242d2f-d0c0-4933-9580-4b42268cd40g

### Expected behavior

_No response_

### To Reproduce

```zsh
. /opt/intel/oneapi/2024.2/oneapi-vars.sh
echo rm -rf build
rm -rf build
CXX=mpiicpx cmake -B build -DBUILD_TESTING=ON -DENABLE_DEEPKS=1 -DTorch_DIR=~/packages/libtorch/share/cmake/Torch/ -Dlibnpy_INCLUDE_DIR=~/packages/libnpy/include
cmake --build build -j`nproc` && sudo cmake --install build
```

### Environment

- OS: Ubuntu 22.04
- Compiler: IntelLLVM 2024.2.0

### Additional Context

_No response_

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

### PR DESCRIPTION
**Pull request by kirk0830**
### Reminder
- [x] Have you linked an issue with this pull request?
- [x] Have you added adequate unit tests and/or case tests for your pull request?
- [x] Have you noticed possible changes of behavior below or in the linked issue?
- [x] Have you explained the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi? (ignore if not applicable)

### Linked Issue
Fix #4673

### Unit Tests and/or Case Tests for my changes
- A unit test is added for each new feature or bug fix.

### What's changed?
- enclose the `#define private public` and `#define protected public` with `#undef private` and `#undef protected`.
- eliminate the impact of `#define private public` on gtest and gmock
- remove unnecessary inclusion of header `<sstream>` which is known to cause compilation crash with `#define private public`-like macro

### Any changes of core modules? (ignore if not applicable)
- Example: I have added a new virtual function in the esolver base class in order to ...

### CODE REVIEW

**Comment by AsTonyshment** [comment]
It seems there are still some issues with the compilation...

**Comment by AsTonyshment** [comment]
Based on my local experiments, it is necessary to move all 
```
#include "gmock/gmock.h" 
#include "gtest/gtest.h" 
```
statements before `#define private public`. This way, the compilation can succeed. @Cstandardlib Maybe you can have a try.

**Comment by Cstandardlib** [comment]
I tested on my machine with oneAPI 2024.2 and encountered many similar errors in tests:
image

It seems to be a systemic problem.
What they all have in common is the use of macros like `#define private public`. Seems that Access specifiers defined before gtest header is included will violate inner definition of gtest.

**Comment by AsTonyshment** [comment]
@Cstandardlib So I mean you have to deal with all these files, and move `#define private public` backwards.

**Review by mohanchen — APPROVED** [review]

**Review by AsTonyshment — APPROVED** [review]

**Comment by AsTonyshment** [comment]
Compilation succeed! LGTM.😀

**Comment by Cstandardlib** [comment]
Build passing😆Thanks！

**Review by mohanchen — APPROVED** [review]

**Pull request merged**
