### PR TITLE
fix: bug when smearing is fixed and npin is 2

### LINKED ISSUE #2655: run abacus-develop/examples/smearing/lcao_fe fail
### Describe the bug

Run second step of abacus-develop/examples/smearing/lcao_fe fail, and the error message is :

```
 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                         NOTICE                           
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 
 Can't find even an electron!
 CHECK IN FILE : OUT.autotest/warning.log
 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                         NOTICE                           
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

### Expected behavior

_No response_

### To Reproduce

_No response_

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by pxlxingliang**

### CODE REVIEW

**Comment by Satinelamp** [comment]
@pxlxingliang 
I got another suggestion:
This error is caused by the the `GlobalV::TWO_EFERMI`, in `input.cpp`, it is set to `false` by default, and in `input_conv.cpp`, it is only set to `true` when `nupdown>10-6`. 
https://github.com/deepmodeling/abacus-develop/blob/dde28673eb998f45f49b826dbdc72b993f0abdb9/source/module_io/input_conv.cpp#L426-L430

In `module_elecstate/elecstate.cpp`, ABACUS makes the wrong judgment to treat only one Fermi energy. But since we are using `nspin =2`, I guess there should be two Fermi energy.
https://github.com/deepmodeling/abacus-develop/blob/dde28673eb998f45f49b826dbdc72b993f0abdb9/source/module_elecstate/elecstate.cpp#L73-L77

So, maybe we should set `GlobalV::TWO_EFERMI=true` when using `nspin=2` in  `input_conv.cpp`?

**Comment by pxlxingliang** [comment]
> @pxlxingliang I got another suggestion: This error is caused by the the `GlobalV::TWO_EFERMI`, in `input.cpp`, it is set to `false` by default, and in `input_conv.cpp`, it is only set to `true` when `nupdown>10-6`.
> 
> https://github.com/deepmodeling/abacus-develop/blob/dde28673eb998f45f49b826dbdc72b993f0abdb9/source/module_io/input_conv.cpp#L426-L430
> 
> In `module_elecstate/elecstate.cpp`, ABACUS makes the wrong judgment to treat only one Fermi energy. But since we are using `nspin =2`, I guess there should be two Fermi energy.
> 
> https://github.com/deepmodeling/abacus-develop/blob/dde28673eb998f45f49b826dbdc72b993f0abdb9/source/module_elecstate/elecstate.cpp#L73-L77
> 
> So, maybe we should set `GlobalV::TWO_EFERMI=true` when using `nspin=2` in `input_conv.cpp`?

Hi @Satinelamp, thanks for your suggestion.
1. This bug is just a mistake in function `iweights()`
2. In code, the variable `TWO_EFERMI` is just related to the setting of `NUPDOWN`, and it is used to refer to whether fix the number of electrons in each spin.

**Comment by Satinelamp** [comment]
> 2. In code, the variable `TWO_EFERMI` is just related to the setting of `NUPDOWN`, and it is used to refer to whether fix the number of electrons in each spin.

So when I use `nspin=2`, abacus still just use only one Fermi energy ?

**Comment by dyzheng** [comment]
> > 2. In code, the variable `TWO_EFERMI` is just related to the setting of `NUPDOWN`, and it is used to refer to whether fix the number of electrons in each spin.
> 
> So when I use `nspin=2`, abacus still just use only one Fermi energy ?

@Satinelamp In general, there is only one Fermi energy in one system. But in some cases, users want to constrain the magnetization of system with parameter "nupdown", while this case won't be the true ground state.

**Review by dyzheng — APPROVED** [review]

**Pull request merged**
