### PR TITLE
Toolchain-2023.5-hotfix：LibRI, Libnpy and others link update

### LINKED ISSUE #3223: Request: update LibRI and other link in Toolchain
### Describe the Code Quality Issue

In toolchain, LibRI, LibComm, Libnpy and CEREAL are downloaded from github release, which need to be updated. 

Also, these released package will always out-of-date, download by using `git clone` is needed, but it's hard to use `git clone` in toolchain method while make toolchain consistent. so more notice information is needed

### Additional Context

_No response_

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

### PR DESCRIPTION
**Pull request by QuantumMisaka**
- libri, libnpy version update
- mirror station in bohrium update
- more notice for libri, libcomm and libnpy in README and scripts

### Reminder
- [x] Have you linked an issue with this pull request?
- [x] Have you noticed possible changes of behavior below or in the linked issue?
- [x] Have you explained the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi? (ignore if not applicable)

### Linked Issue
Fix #3223 

### What's changed?
- update version of Libnpy and LibRI
- update mirror dataset link
- update README and more information notice

### CODE REVIEW

**Review by dyzheng — APPROVED** [review]
Thanks for your contribution, can you help us to build auto test of toolchain?

**Comment by QuantumMisaka** [comment]
> Thanks for your contribution, can you help us to build auto test of toolchain?

An easiest way to auto test is just using `toolchain*.sh` and `build_abacus*.sh` to build abacus, source `abacus_env.sh` and run this abacus in some example. This version of Toolchain turn-off `deepks` and `libri` option for default due to give user a better first-time usage, so this function may need to test in some specific way. 

I consider that an ABACUS mirror (docker or others) with toolchain installation can be used for auto test ?

**Comment by QuantumMisaka** [comment]
> Thanks for your contribution, can you help us to build auto test of toolchain?

I have viewed some auto test failure of toolchain, the problem is weird and should not happen in the newest version of toolchain. take intel toolchain as example, the toolchain usage is :
1. cd toolchain
2. sh toolchain_intel.sh
3. sh build_abacus_intel.sh (that's for default setting, which is NOT include deepks and LibRI in default NOW)
4. source abacus_env.sh

May this steps need check-out ?

**Comment by QuantumMisaka** [comment]
@caic99 @dyzheng If there is not any problem, can this link update PR be merged ?

**Review by dyzheng — APPROVED** [review]
Toolchain is very useful, thanks for your contribution.

**Pull request merged**
