### PR TITLE
Test: update 58 warnings ref and CI test will fail with warning

### LINKED ISSUE #3242: Integrated tests pose warnings
### Describe the Testing Issue

[warningtot2023_11_22_13_58.txt](https://github.com/deepmodeling/abacus-develop/files/13434964/warningtot2023_11_22_13_58.txt)
relate to the issues of #2844  "On November 21, 2023, I collected all available PRs on GitHub, categorized them as the warningtot2023_11_22_13_58.txt, and identified certain warnings that may require contributors to address.
______
The first case is as follows: 
PR #2998  by @Qianruipku  has introduced some new warnings, although they appeared and disappeared before the latest introduction.
```
...
PR 3008 
PR 2998 2023-10-09T07:20:18.4148669Z 1: [WARNING   ]  totalstressref cal=1409.56340100 ref=1409.54391900 deviation=-0.01948200
...up to now appear
```
- [x] 101_PW_15_pseudopots_LibxcLDA
- [x] 103_PW_15_CS_CF
- [x] 103_PW_15_CS_CF_bspline
- [x] 103_PW_OU_CS_CF
- [x] 107_PW_outWfcPw
- [x] 107_PW_outWfcR
- [ ] 108_PW_RE
- [x] 108_PW_RE_MG
- [ ] 109_PW_CR_fix_ac
- [ ] 109_PW_CR_fix_b
- [ ] 109_PW_CR_fix_bc
- [ ] 109_PW_CR_fix_c
- [ ] 109_PW_CR_moveatoms
- [x] 110_PW_SY
- [x] 112_PW_dipole
- [x] 112_PW_efield
- [x] 113_PW_gatefield
- [x] 115_PW_sol_H2O
- [x] 120_PW_KP_MD_MSST
- [x] 120_PW_KP_MD_MSST_level2
- [ ] 120_PW_KP_MD_NPT
- [ ] 120_PW_KP_MD_NVT
- [ ] 170_PW_MD_1O
- [ ] 170_PW_MD_2O
- [x] 201_NO_KP_DJ_CF_CS_GaAs
- [x] 204_NO_KP_AFM
- [x] 270_NO_MD_1O
______
The second case is as follows:
PR #3178 @wenfei-li has introduced a new warnings as 
```
...
PR 3176 
PR 3178 2023-11-09T06:28:13.2550640Z 1: [WARNING   ]  etotref cal=-200.93490284 ref=-200.93404758 deviation=0.00085526
...up to now
```
- [ ] 101_PW_15_paw
______
The third case is as follows:
PR #3122 @YuLiu98  has introduced a new warnings as 
```
...
PR 3139 
PR 3122 2023-11-03T04:12:42.2978862Z 1: [WARNING   ]  totalstressref cal=763.26430700 ref=763.25719100 deviation=-0.00711600
PR 3144 
PR 3145 2023-11-03T14:42:51.5758164Z 1: [WARNING   ]  totalstressref cal=763.26434700 ref=763.25719100 deviation=-0.00715600
...up to now
```
- [ ] 101_PW_upf201_uspp_NaCl
______
The fourth case is as follows:
PR #3175 @pxlxingliang has introduced some new warnings：but these warnings had appeared before and disappeared at some point.
```
...
PR 3172 
PR 3175 2023-11-08T07:02:03.8821639Z 1: [WARNING   ]  totalforceref cal=5.19522000 ref=5.19483200 deviation=-0.00038800
PR 3134 
PR 3177 2023-11-09T01:40:44.4158332Z 1: [WARNING   ]  totalforceref cal=5.19522000 ref=5.19483200 deviation=-0.00038800
...up to now
```
- [ ] 102_PW_BPCG
- [x] 184_PW_BNDKPAR_SDFT_ALL
- [x] 184_PW_BNDKPAR_SDFT_MALL
______
The fifth case is as follows:
PR #3081 by @maki49  has introduced some new warnings as:
```
...
PR 3105 
PR 3081 2023-10-25T17:22:09.7680675Z 1: [WARNING   ]  etotref cal=-145.79150761 ref=-145.79681340 deviation=-0.00530579
PR 3108 
PR 3109 2023-10-26T09:27:52.6434574Z 1: [WARNING   ]  etotref cal=-145.79150761 ref=-145.79681340 deviation=-0.00530579
...appear up to now
```
- [x] 207_NO_KP_OHS_SPIN4
- [x] 207_NO_KP_OTdH
- [x] 213_NO_mulliken
______
The sixth case is as follows:
PR #3133 @WHUweiqingzhou The warning may refresh the ref.data to eliminate the warning.
```
...
PR 3127 
PR 3133 2023-11-02T03:49:49.1430259Z 1: [WARNING   ]  totalstressref cal=4160.38232200 ref=4160.36613500 deviation=-0.01618700
...appear up to now
```
- [ ] 281_NO_KP_HSE
- [ ] 286_NO_KP_CR_HSE
- [ ] 803_PW_LT_bcc
- [ ] 810_PW_LT_fco
- [x] 812_PW_LT_sm
______
The last case is as follows: Some warnings appear consistently because GitHub only supports data for up to three months. The warning may refresh the ref.data to eliminate the warning.
- [ ] 109_PW_CR
- [ ] 109_PW_CR_fix_a
- [ ] 109_PW_CR_fix_ab
- [ ] 109_PW_CR_fix_abc
- [x] 116_PW_scan_Si2
- [ ] 116_PW_scan_Si2_nspin2
- [ ] 150_PW_15_CR_VDW3
- [x] 601_NO_TDDFT_CO
- [x] 801_PW_LT_sc
- [ ] 802_PW_LT_fcc
- [ ] 807_PW_LT_bct

update state by @hongriTianqi according to https://github.com/deepmodeling/abacus-develop/actions/runs/7318359302/job/19934906652 at 2023-12-25
 

### Additional Context

[Aotogetwarn.txt](https://github.com/deepmodeling/abacus-develop/files/13435834/Aotogetwarn.txt)
the bash script that I have used to collect the warnings, in order to use it one need download some of the related PR test with zip file and run the bash in the linux shell. 

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

### LINKED ISSUE #3414: In the CI test some warning get different value between github test
### Describe the Testing Issue

In the CI test some warning get different value between github test, 
____
101_PW_upf201_uspp_NaCl 
mywarn    [WARNING   ]  totalforceref cal=9.44457600 ref=9.44612000 deviation=0.00154400
githup  1: [WARNING   ]  totalforceref cal=9.44971600 ref=9.44612000 deviation=-0.00359600
____
281_NO_KP_HSE 与github
mywarn [WARNING   ]  totalstressref cal=4160.37924100 ref=4160.36613500 deviation=-0.01310600
githup   [WARNING   ]  totalstressref cal=4160.37931600 ref=4160.36613500 deviation=-0.01318100
____
286_NO_KP_CR_HSE
mywarn    [WARNING   ]  etotref cal=-192.65701443 ref=-192.65714944 deviation=-0.00013501
githup  1: [WARNING   ]  etotref cal=-192.65701432 ref=-192.65714944 deviation=-0.00013512
____
I want to change the result.ref, which comfirm before it avalable, but some test get different value and I don't now how to solve it.
this issue related PR is #3412  and #3382 , it also related to the issues before #2844

### Additional Context

_No response_

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

### LINKED ISSUE #4187: Question: why there are always plenty of warnings in integrated test?
### Details

For any PRs, if dive into record of integrated test, one can easily find for example, the warning like:
```
1: [ RUN      ] 108_PW_RE
1: [----------] do 2step relax with cg  mixing_gg0=1.5
1: [WARNING   ]  etotref cal=-211.51539144 ref=-211.60980465 deviation=-0.09441321
1: [----------] Time elapsed: 1.968 seconds
1: 
1: [ RUN      ] 108_PW_RE_MB
1: [----------] test BFGS method with diamond Si, symmetry=on
1: [      OK  ]  etotref
1: [      OK  ]  etotperatomref
1: [WARNING   ]  totalforceref cal=6.58284000 ref=6.58297800 deviation=0.00013800
1: [----------] Time elapsed: 1.848 seconds
1: 
1: [ RUN      ] 108_PW_RE_MG
1: [----------] test CG method with diamond Si, symmetry=on
1: [      OK  ]  etotref
1: [      OK  ]  etotperatomref
1: [      OK  ]  totalforceref
1: [      OK  ]  pointgroupref
1: [      OK  ]  spacegroupref
1: [      OK  ]  nksibzref
1: [----------] Time elapsed: 1.663 seconds
1: 
1: [ RUN      ] 108_PW_RE_NEW
1: [----------] test for new relaxation method with cg  mixing_gg0=1.5
1: [      OK  ]  etotref
1: [      OK  ]  etotperatomref
1: [WARNING   ]  totalforceref cal=0.07393800 ref=0.07307800 deviation=-0.00086000
1: [----------] Time elapsed: 7.401 seconds
1: 
1: [ RUN      ] 108_PW_RE_PINT_RKS
1: [----------] integrated test 108_PW_RE_NEW with psi_initializer init_wfc nao (nspin = 1, cell-relax)
1: [      OK  ]  etotref
1: [      OK  ]  etotperatomref
1: [WARNING   ]  totalforceref cal=0.07397000 ref=0.07311200 deviation=-0.00085800
1: [----------] Time elapsed: 12.215 seconds
1: 
1: [ RUN      ] 109_PW_CR
1: [----------] test cell-relax for atom can't move
1: [      OK  ]  etotref
1: [      OK  ]  etotperatomref
1: [      OK  ]  totalforceref
1: [      OK  ]  totalstressref
1: [----------] Time elapsed: 2.280 seconds
1: 
1: [ RUN      ] 109_PW_CR_fix_a
1: [----------] test cell-relax for the fixed a axe
1: [WARNING   ]  etotref cal=-211.82346586 ref=-211.82078123 deviation=0.00268463
1: [----------] Time elapsed: 2.149 seconds
1: 
1: [ RUN      ] 109_PW_CR_fix_ab
1: [----------] test cell-relax for the fixed ab axe
1: [WARNING   ]  etotref cal=-211.82181948 ref=-211.81909770 deviation=0.00272178
1: [----------] Time elapsed: 2.174 seconds
1: 
1: [ RUN      ] 109_PW_CR_fix_abc
1: [----------] test cell-relax for the fixed abc axe
1: [WARNING   ]  etotref cal=-211.81790238 ref=-211.81[511](https://github.com/deepmodeling/abacus-develop/actions/runs/9146108526/job/25145854898#step:6:512)180 deviation=0.00279058
1: [----------] Time elapsed: 1.260 seconds
1: 
1: [ RUN      ] 109_PW_CR_fix_ac
1: [----------] test cell-relax for the fixed ac axe
1: [WARNING   ]  etotref cal=-211.82181944 ref=-211.81909772 deviation=0.00272172
1: [----------] Time elapsed: 2.299 seconds
1: 
1: [ RUN      ] 109_PW_CR_fix_b
1: [----------] test cell-relax for the fixed b axe
1: [WARNING   ]  etotref cal=-211.82346587 ref=-211.82078125 deviation=0.00268462
1: [----------] Time elapsed: 2.179 seconds
1: 
1: [ RUN      ] 109_PW_CR_fix_bc
1: [----------] test cell-relax for the fixed bc axe
1: [WARNING   ]  etotref cal=-211.82181946 ref=-211.81909772 deviation=0.00272174
1: [----------] Time elapsed: 1.918 seconds
1: 
1: [ RUN      ] 109_PW_CR_fix_c
1: [----------] test cell-relax for the fixed c axe
1: [WARNING   ]  etotref cal=-211.82346584 ref=-211.82078124 deviation=0.00268460
1: [----------] Time elapsed: 2.189 seconds
1: 
1: [ RUN      ] 109_PW_CR_moveatoms
1: [----------] test cell-relax for atom can move
1: [WARNING   ]  etotref cal=-211.82472837 ref=-211.82207276 deviation=0.00265561
1: [----------] Time elapsed: 1.489 seconds
```
The deviation seems small but where does it comes from? Result from UB?

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

### PR DESCRIPTION
**Pull request by WHUweiqingzhou**
Close #4187
Close #3414
Close #3242

### The List of Changes
1. Update to commit 494fca4, there are 58 warnings in github CI tests. This PR update 58 reference data.
2. add threshold file in some numerically unstable tests, including `104_PW_NC_magnetic` and `286_NO_KP_CR_HSE`, `102_PW_CG_GPU/102_PW_DA_davidson_GPU/102_PW_BPCG_GPU`.
3. After this PR, CI test will fail once fatal error or warning happen. (Before this PR, CI test fails only when fatal error occurs.)

### Please Notice that
1. After this PR, warnings are also unaccepted as same as the fatal errors. Due to the potential numerical instability inherent to ABACUS, modifications might lead to some unrelated numerical fluctuations, and lead to warning. If a PR fails due to warning. I will suggest that PR should be reviewed by at least 3 developers. If all reviewers think PR is OK. You can update corresponding references and make your PR pass.
2. PR #4450 from @pxlxingliang enable one can prepare a `threshold` in each cases directory. For numerically unstable test cases—those that yield different results on different runs, one can establish a tolerance level to relax the error conditions by editing `threshold` file.
---
58 Warning from CI test now:
```
Warning: NG]    58 test cases out of 1227 failed.
1: 101_PW_15_lowz
1: 101_PW_15_paw
1: 101_PW_blps_pseudopots
1: 101_PW_upf201_uspp_NaCl
1: 101_PW_Coulomb
1: 102_PW_BPCG
1: 103_PW_CF_CS_S1_smallg
1: 103_PW_CF_CS_S2_smallg
1: 104_PW_NC_magnetic
1: 105_PW_FD_smearing
1: 105_PW_GA_smearing
1: 107_PW_outWfcR
1: 108_PW_RE
1: 108_PW_RE_MB
1: 109_PW_CR_fix_a
1: 109_PW_CR_fix_ab
1: 109_PW_CR_fix_abc
1: 109_PW_CR_fix_ac
1: 109_PW_CR_fix_b
1: 109_PW_CR_fix_bc
1: 109_PW_CR_fix_c
1: 109_PW_CR_moveatoms
1: 110_PW_SY_symmetry_LiRh
1: 111_PW_elec_add
1: 111_PW_elec_minus
1: 111_PW_S2_elec_add
1: 111_PW_S2_elec_minus
1: 115_PW_sol_H2
1: 116_PW_scan_Si2_nspin2
1: 120_PW_KP_MD_NPT
1: 120_PW_KP_MD_NVT
1: 133_PW_DJ_PK
1: 150_PW_15_CR_VDW3
1: 170_PW_MD_1O
1: 170_PW_MD_2O
1: 180_PW_SDFT_10S_M
1: 180_PW_SDFT_10S_P
1: 181_PW_SDFT_5D10S
1: 182_PW_SDFT_ALL
1: 183_PW_MD_SDFT_10S
1: 183_PW_MD_SDFT_5D10S
1: 183_PW_MD_SDFT_ALL
1: 184_PW_BNDPAR_SDFT_10S
1: 184_PW_BNDPAR_SDFT_5D10S
1: 184_PW_KPAR_SDFT_ALL
1: 185_PW_SDFT_10D10S_METHD2
1: 185_PW_SDFT_10S_METHD2
1: 186_PW_SDOS_10D10S
1: 186_PW_SNLKG_10D10S
1: 250_NO_KP_CR_VDW3ABC
1: 281_NO_KP_HSE
1: 286_NO_KP_CR_HSE
1: 384_NO_GO_S1_HSE_loop0_PU
1: 601_NO_TDDFT_H2_restart
1: 601_NO_TDDFT_CO
1: 601_NO_TDDFT_CO_occ
1: 803_PW_LT_bcc
1: 806_PW_LT_st
```

### CODE REVIEW

**Comment by caic99** [comment]
@WHUweiqingzhou There are other scripts named Autotest; should this PR also updates them?

**Comment by WHUweiqingzhou** [comment]
> @WHUweiqingzhou There are other scripts named Autotest; should this PR also updates them?

What `Autotest` you mean?

**Comment by caic99** [comment]
> What `Autotest` you mean?

Under tests/deepks

**Comment by WHUweiqingzhou** [comment]
> > What `Autotest` you mean?
> 
> Under tests/deepks



> > What `Autotest` you mean?
> 
> Under tests/deepks



> > What `Autotest` you mean?
> 
> Under tests/deepks

Done.

**Comment by WHUweiqingzhou** [comment]
> > What `Autotest` you mean?
> 
> Under tests/deepks

Done.

**Review by Qianruipku — APPROVED** [review]

**Pull request closed without merging**
