### PR TITLE
Refactor: Modify class `BaseMatrix`

### PR DESCRIPTION
**Pull request by DylanWRh**
### Reminder
- [x] Have you explained the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi? (ignore if not applicable)

### What's changed?

Refactor the code in class `BaseMatrix` to be safer.

- Add allocation judgement and possible memory release in `operator=` to avoid potential memory waste
- Add debug statement to check if `value_begin` is `nullptr` in functions such as `add_array`, `add_element`, and `get_value`.
- Modify documentation for `add_array` function to avoid potential misunserstanding

### CODE REVIEW

**Review by dyzheng — APPROVED** [review]
LGTM

**Comment by dyzheng** [comment]
@DylanWRh please simplify your commit history

**Comment by dyzheng** [comment]
@DylanWRh please simplify your commit history

**Comment by DylanWRh** [comment]
> @DylanWRh please simplify your commit history

OK! I'll pay attention to that in future PRs.

**Pull request merged**
