### PR TITLE
Fix: INPUT parameter dft_functional with any upper or lower letter

### PR DESCRIPTION
**Pull request by PeizeLin**
Fix issue #2945.
In INPUT, dft_functional=hse or dft_functional=HSE or even dft_functional=HsE will work successfully now.

### CODE REVIEW

**Review by hongriTianqi — COMMENTED** [review]
could you please add a unit.test to make sure that this feature works in future

**Comment by maki49** [comment]
> could you please add a unit.test to make sure that this feature works in future

There's no new feature, just a call of `std::transform` in the \<algorithm\> header.

**Review by dyzheng — APPROVED** [review]

**Review by dyzheng — COMMENTED** [review]
You can add unittest or change some INPUT in HSE related test cases in tests/integrate/28xxx

**Comment by PeizeLin** [comment]
> You can add unittest or change some INPUT in HSE related test cases in tests/integrate/28xxx

`dft_functional` in 285_NO_KP_RE_HSE is changed to `hsE`.

**Review by dyzheng — APPROVED** [review]

**Pull request merged**
