### PR TITLE
Docs: add introductions to ci/cd and new modules 

### PR DESCRIPTION
**Pull request by caic99**

### CODE REVIEW

**Review by WHUweiqingzhou — APPROVED** [review]
Good Docs! Thanks for your contributions!

**Comment by Flying-dragon-boxing** [comment]
How can I use a third-party library that is not in ubuntu's software repo? Searched in Ubuntu repo but nothing found.
[PEXSI Library](https://pexsi.readthedocs.io/en/latest/)

**Comment by caic99** [comment]
> How can I use a third-party library that is not in ubuntu's software repo? Searched in Ubuntu repo but nothing found.
> 
> [PEXSI Library](https://pexsi.readthedocs.io/en/latest/)

Hi @Flying-dragon-boxing ,
In this case, you have to compile and install the package from source code.

**Comment by Flying-dragon-boxing** [comment]
> > How can I use a third-party library that is not in ubuntu's software repo? Searched in Ubuntu repo but nothing found.
> > [PEXSI Library](https://pexsi.readthedocs.io/en/latest/)
> 
> Hi @Flying-dragon-boxing , In this case, you have to compile and install the package from source code.

Add building scripts to the dockerfile?

**Comment by caic99** [comment]
> Add building scripts to the dockerfile?

@Flying-dragon-boxing Yes. Take ELPA as an example: https://github.com/deepmodeling/abacus-develop/blob/develop/Dockerfile.intel#L35-L46

**Comment by Flying-dragon-boxing** [comment]
> > Add building scripts to the dockerfile?
> 
> @Flying-dragon-boxing Yes. Take ELPA as an example: https://github.com/deepmodeling/abacus-develop/blob/develop/Dockerfile.intel#L35-L46

Got it! Thank you!

**Review by dyzheng — APPROVED** [review]
LGTM

**Comment by WHUweiqingzhou** [comment]
this PR solves #3614

**Pull request merged**
