### PR TITLE
Doc: update issue templates

### PR DESCRIPTION
**Pull request by hongriTianqi**

### CODE REVIEW

**Comment by caic99** [comment]
Hi @hongriTianqi ,
How about not changing existed tags? Since tags can not automatically be transferred from the old ones to the new ones, this may cause inconsistency between issues of the same category.

**Comment by hongriTianqi** [comment]
> Hi @hongriTianqi ,
> How about not changing existed tags? Since tags can not automatically be transferred from the old ones to the new ones, this may cause inconsistency between issues of the same category.

Hi @caic99, new tags are preferred when new issue templates are applicable.

**Review by caic99 — APPROVED** [review]

**Review by dyzheng — APPROVED** [review]

**Comment by hongriTianqi** [comment]
@LiuXiaohui123321 Could you please help review this PR. The results can be temporarily checked at https://github.com/hongriTianqi/issue_template/issues/new/choose. Thanks!

**Comment by LiuXiaohui123321** [comment]
> @LiuXiaohui123321 Could you please help review this PR. The results can be temporarily checked at https://github.com/hongriTianqi/issue_template/issues/new/choose. Thanks!

The revised tag categorization looks better. Do these tags cover the content of previously existing issues? In other words, are there any missing tags for the content of previous issues?

**Comment by hongriTianqi** [comment]
> > @LiuXiaohui123321 Could you please help review this PR. The results can be temporarily checked at https://github.com/hongriTianqi/issue_template/issues/new/choose. Thanks!
> 
> The revised tag categorization looks better. Do these tags cover the content of previously existing issues? In other words, are there any missing tags for the content of previous issues?

No missing tags, but some minor changes, for example "bug" to "bug report", "feature" to "feature request"

**Pull request merged**
