### PR TITLE
Refactor: 1. add nscf in ESolver_KS_PW, 2. move psi from GlobalC::wf to ESolver

### PR DESCRIPTION
**Pull request by dyzheng**

### CODE REVIEW

**Review by mohanchen — APPROVED** [review]

**Comment by Qianruipku** [comment]
#include "src_lcao/record_adj.h"
#include "src_lcao/local_orbital_charge.h"
#include "src_lcao/local_orbital_wfc.h"
#include "src_lcao/LCAO_hamilt.h"
These should not exist in esolver.h

**Comment by Qianruipku** [comment]
1. Maybe you did not see questions in #923. Please think over it.
2. Besides, why "this->phsol = new hsolver::HSolverPW(pbas);" are in beforescf but not in Init. It means in every md step, a new hsolver should be deleted and construncted. Maybe you consider that every md step different hsolver will be used?
3. nscf should  be defined in esolver_ks but not in esolver? If it is a temporary treatment, please add some annotations. Also psi should be defined in esolver_fp but not in esolver.h since classical potential do not know what psi is.

**Comment by Qianruipku** [comment]
#include "src_io/write_wfc_realspace.h"
#include "src_io/winput.h"
#include "src_io/numerical_descriptor.h"
#include "src_io/numerical_basis.h"
#include "src_io/to_wannier90.h"
#include "src_io/berryphase.h"
It should be careful to add head files.  So far as I know berryphase.h contain both pw and lcao. It will make pw program depend of lcao. Maybe it is a temporary treatment and should be considered in the future.

**Comment by dyzheng** [comment]
> #include "src_lcao/record_adj.h" #include "src_lcao/local_orbital_charge.h" #include "src_lcao/local_orbital_wfc.h" #include "src_lcao/LCAO_hamilt.h" These should not exist in esolver.h

Thank for your reply, these code are not supposed to exist, maybe there is any mistake in merge operation, I will fix that.

**Review by Qianruipku — APPROVED** [review]

**Pull request merged**
