### PR TITLE
Reduce the device memory consumption of stress calculation

### LINKED ISSUE #3931: Perf: Large memory cost of Force&Stress calculations result in Out-Of-Memory Issues
### Details

Large memory cost of Force&Stress calculations result in Out-Of-Memory Issue. I upload an example from user in the attachment, that case meets a OOM issue in DCU, since DCU's memory is limited.

[example.zip](https://github.com/deepmodeling/abacus-develop/files/14901149/example.zip)

### Task list for Issue attackers (only for developers)

- [ ] Reproduce the performance issue on a similar system or environment.
- [ ] Identify the specific section of the code causing the performance issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified performance issue.
- [ ] Implement the chosen solution to address the performance issue.
- [ ] Test the implemented solution to ensure it improves performance without introducing new issues.
- [ ] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

### PR DESCRIPTION
**Pull request by denghuilu**
### Reminder
- [x] Have you linked an issue with this pull request?
- [ ] Have you added adequate unit tests and/or case tests for your pull request?
- [ ] Have you noticed possible changes of behavior below or in the linked issue?
- [ ] Have you explained the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi? (ignore if not applicable)

This PR introduces a new cal_stress mode designed to gently reduce GPU memory consumption during stress calculations under certain conditions. This is a variable that must be explicitly configured, aiming mainly to help devices with smaller memory, like the DCU, manage stress computations for large systems more effectively.

The si_16 GPU example achieved an 83.5% reduction in memory consumption during stress calculations by setting cal_stress to 2.

### Linked Issue
Close #3931 

### Unit Tests and/or Case Tests for my changes
- A unit test is added for each new feature or bug fix.

### What's changed?
Change the INPUT param cal_stress from bool to int, eg: 
```
cal_stress
Type: Integer
Description:
0: no calculation of the stress at the end of the electronic iteration
1: calculate the stress at the end of the electronic iteration
2: calculate the stress by utilizing the CPU to execute the cal_dbecp_noevc_nl_host_op function.
Default: 1 if calculation is cell-relax, 0 otherwise.
```
### Any changes of core modules? (ignore if not applicable)
- Example: I have added a new virtual function in the esolver base class in order to ...

### CODE REVIEW

**Review by dyzheng — COMMENTED** [review]
I don't think calculate stress on CPU is a good idea when GPU device is available.

**Comment by denghuilu** [comment]
> I don't think calculate stress on CPU is a good idea when GPU device is available.

Sorry about the misleading, given the background of this issue, here’s a more detailed outline of what this PR entails:

- This PR introduces a new `cal_stress` mode designed to decrease GPU memory usage during specific stress calculations by shifting some calculations to the CPU.
- This setting must be explicitly enabled.
- Importantly, this PR does not transfer all stress calculations to the CPU. It specifically targets only the `cal_dbecp_noevc_nl_op` function, which consumes the most device memory, while other processes like the vkb calculation and gemm continue to operate on the GPU/DCU.
- Performance tests on the 3070 have confirmed that this PR has only a minimal impact on overall performance.

**Comment by Qianruipku** [comment]
This is a temporary modification because DCU currently lacks sufficient memory to simulate a 32-atom system. However, resolving the memory issue would require significant modifications to the stress program. If future modifications to stress result in lower memory consumption, this temporary measure can be removed.

**Review by dyzheng — COMMENTED** [review]
I recommand not to change the parameter `cal_stress`, you would better change the calculating method directly, because the old method is not good for DCU/GPU calculation.

**Comment by Qianruipku** [comment]
This PR can be put on hold for now. If the new stress algorithm can be implemented quickly and can reduce memory consumption without compromising efficiency, then this PR won't be needed anymore.

**Comment by WHUweiqingzhou** [comment]
Issue #4031 also concerns this problem.

**Pull request closed without merging**
