### PR TITLE
refactor : update the output of H(k), S(k), H(R), S(R) and r(R); also provide more information in the documentation

### LINKED ISSUE #1257: Segfault in gamma_only LCAO calculation when out_mat_hs2==1
### Describe the bug

There is a segfault in gamma_only LCAO calculation when out_mat_hs2==1.

### Expected behavior

_No response_

### To Reproduce

_No response_

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by wenfei-li**

### CODE REVIEW

**Comment by Fadelis98** [comment]
Thanks for your updating! However the problem here #1261   is not the format of sparse matrix, but the physical meaning of the matrix.

In the notation of abacus paper `10.1016/j.commatsci.2015.07.004`, we have $\mu$ = { $\alpha, i, l, m, \zeta$ }, so that given a matrix $H(R)$, the element $H[\mu][\nu]$ represents $\langle\Phi_\mu |H|\Phi_\nu \rangle$. Now in the abacus programme, the matrix index is just single number, while the relationship between matrix index $\mu$ and physical indexes ${\alpha, i, l, m, \zeta\}$ is unknown, which is expected to be explained in the document.

**Comment by wenfei-li** [comment]
> Thanks for your updating! However the problem here #1261 is not the format of sparse matrix, but the physical meaning of the matrix.
> 
> In the notation of abacus paper `10.1016/j.commatsci.2015.07.004`, we have μ = { α,i,l,m,ζ }, so that given a matrix H(R), the element H[μ][ν] represents ⟨Φμ|H|Φν⟩. Now in the abacus programme, the matrix index is just single number, while the relationship between matrix index μ and physical indexes α,i,l,m,ζ is unknown, which is expected to be explained in the document.

We used to write such information in a separate file (you may want to check this out: https://github.com/abacusmodeling/abacus-develop/issues/163).

**Comment by Fadelis98** [comment]
> > Thanks for your updating! However the problem here #1261 is not the format of sparse matrix, but the physical meaning of the matrix.
> > In the notation of abacus paper `10.1016/j.commatsci.2015.07.004`, we have μ = { α,i,l,m,ζ }, so that given a matrix H(R), the element H[μ][ν] represents ⟨Φμ|H|Φν⟩. Now in the abacus programme, the matrix index is just single number, while the relationship between matrix index μ and physical indexes α,i,l,m,ζ is unknown, which is expected to be explained in the document.
> 
> We used to write such information in a separate file (you may want to check this out: [abacusmodeling#163](https://github.com/abacusmodeling/abacus-develop/issues/163)).

That's helpful, thanks!

**Comment by wenfei-li** [comment]
there are some conflicts and other stuff to be considered. I'll close this pr and start a new one later

**Pull request closed without merging**
