### PR TITLE
Refactor: Remove SPIN1_CHG file

### LINKED ISSUE #1983: Too many output when out_chg=1.
### Background
SPIN1_CHG, SPIN1_CHG.cube, tmp_SPIN1_CHG, and tmp_SPIN1_CHG.cube contain similar information, so they should be unified into one file in order to save space.
### Describe the solution you'd like
Merge SPIN1_CHG and SPIN1_CHG.cube into the same format, for example, the CHGCAR format used in VASP.
In order to do nscf calculation, we can write the Fermi energy in the comment part of CHGCAR.
Moreover, other quantities on real space points, such as SPIN1_POT and ElecStaticPot, should be unified into the same format, too.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by sunliang98**
1. Remove `SPIN1_CHG` file from ABACUS.
2. Modify the format of SPIN1_CHG.cube as follows, so that it contains nspin and Fermi energy.
   `Cubefile created from ABACUS SCF calculation`
   `1 (nspin) 0.129177 (fermi energy, in Ry)`
3. Nscf calculation relies on `SPIN1_CHG.cube` instead of `SPIN1_CHG` now.
4. Update corresponding integrate tests and unit tests.

### CODE REVIEW

**Review by dyzheng — COMMENTED** [review]
It seems .cube file is larger than old SPIN1.CHG file.

**Comment by dyzheng** [comment]
Most of users don't need visiable charge density file, maybe keep old version and add a choice for users is better? 
Such as "out_chg = 1 for SPIN1.CHG and 2 for SPIN1.CHG.cube", and both of them can be used for restarting.

**Comment by dyzheng** [comment]
Another concern of me is many users rely on interface or workflow software to work with ABACUS, change default behavier will perplex them.

**Comment by mohanchen** [comment]
Do we have a list of workflow software that may be affected by outputs of ABACUS?

**Comment by dyzheng** [comment]
> Do we have a list of workflow software that may be affected by outputs of ABACUS?

I don't know any official software dealing with "SPIN1_CHG" file, some users may have their own scripts for restarting calculation.

**Review by dyzheng — APPROVED** [review]

**Comment by sunliang98** [comment]
> Most of users don't need visiable charge density file, maybe keep old version and add a choice for users is better? Such as "out_chg = 1 for SPIN1.CHG and 2 for SPIN1.CHG.cube", and both of them can be used for restarting.

If necessary, we can also keep the old version.
However, I think we should determine which file to use for nscf calculation. Otherwise, if the contents of SPIN1_CHG and SPIN1_CHG.cube files are different, it may cause confusion to users, although this is unlikely to happen.

**Comment by dyzheng** [comment]
> > Most of users don't need visiable charge density file, maybe keep old version and add a choice for users is better? Such as "out_chg = 1 for SPIN1.CHG and 2 for SPIN1.CHG.cube", and both of them can be used for restarting.
> 
> If necessary, we can also keep the old version. However, I think we should determine which file to use for nscf calculation. Otherwise, if the contents of SPIN1_CHG and SPIN1_CHG.cube files are different, it may cause confusion to users, although this is unlikely to happen.

I agree.

**Pull request merged**
