### PR TITLE
Feature: EXX numerical type is distinguished by new input parameter "exx_real_number"

### PR DESCRIPTION
**Pull request by dyzheng**
1. change distinguishing between exx_lri_double and exx_lri_complex from GlobalV::GAMMA_ONLY_LOCAL to GlobalC::exx_info.info_ri.real_number

### CODE REVIEW

**Comment by xinyangd** [comment]
Do you mind briefly explain why this update is necessary? Does it fix an existing bug?

**Comment by dyzheng** [comment]
> Do you mind briefly explain why this update is necessary? Does it fix an existing bug?

It modified by author @PeizeLin , the purpose of this PR is set numerial type of EXX matrix element by user instead of by input parameter "gamma_only".
In multi-k cases, the matrix elements are in type "complex<double>",  but most of them have only real part, which can be changed to "double" type.
There will be a significant improvement for efficiency of EXX calculation if the PR can be merged. 

By the way, is there any issue for efficient comparation between old EXX and new EXX module?

**Comment by caic99** [comment]
@dyzheng Did you add corresponding docs?

**Comment by dyzheng** [comment]
> @dyzheng Did you add corresponding docs?

Documentations has been added, please review this PR @caic99 @xinyangd

**Review by xinyangd — APPROVED** [review]

**Pull request merged**
