### PR TITLE
refactor: add ncpp in atom_spec.h

### PR DESCRIPTION
**Pull request by hongriTianqi**
cut the derivative of class Atom from class Atom_pseudo

### CODE REVIEW

**Comment by mohanchen** [comment]
Is it better to change the name of Atom_pseudo to ncpp (norm-conserving pseudopotentials), we may have other psedudopotentials in the future, such as ultrasoft pseudopotentials, or PAW method, where do we plan to put them?

**Comment by hongriTianqi** [comment]
> Is it better to change the name of Atom_pseudo to ncpp (norm-conserving pseudopotentials), we may have other psedudopotentials in the future, such as ultrasoft pseudopotentials, or PAW method, where do we plan to put them?

I notice that there's already a class of pseudo_nc which is dedicated for norm-conserving pseudo potentials. The class Atom_pseudo derives pseudo_nc. So I think that we might need to break again this derivation of Atom_pseudo from pseudo_nc, because then we might be able to add uspp and paw as multistate of Atom_pseudo.

**Review by dyzheng — APPROVED** [review]
This PR is very well.
As a caution, you would better update to latest develop branch and rerun CI.

**Comment by caic99** [comment]
> This PR is very well. As a caution, you would better update to latest develop branch and rerun CI.

Hi @dyzheng ,
I think this is unnecessary, because the codes for CI is the state after merging, but not the PR branch without modifications from upstream. Just FYI.

**Review by Qianruipku — APPROVED** [review]

**Pull request merged**
